package analyzer

import "github.com/Bluezly/CIRadar/internal/model"

func catalogOSSDataRules() []catalogRuleSpec {
	return []catalogRuleSpec{
		ossRule("oss-postgres-too-many-connections", model.CategoryResourceExhaustion, "PostgreSQL", "connect", "connection-slots-exhausted", 97, "resource", "Reduce leaked/idle connections or adjust pool and server connection limits based on measured concurrency.", "FATAL: (?:sorry, )?too many clients already|remaining connection slots are reserved"),
		ossRule("oss-postgres-starting-up", model.CategoryRunnerFailure, "PostgreSQL", "connect", "database-starting-up", 97, "service-readiness", "Wait for database recovery/readiness and inspect PostgreSQL startup logs if recovery does not complete.", "FATAL:\\s+the database system is starting up|database system is not yet accepting connections"),
		ossRule("oss-postgres-lock-timeout", model.CategoryConcurrencyConflict, "PostgreSQL", "query", "lock-timeout", 97, "concurrency", "Identify the blocking transaction and reduce lock scope/duration before increasing lock timeouts.", "canceling statement due to lock timeout|could not obtain lock on relation"),
		ossRule("oss-postgres-serialization", model.CategoryConcurrencyConflict, "PostgreSQL", "transaction", "serialization-failure", 97, "concurrency", "Retry the transaction with bounded application-level retry logic and inspect contention hot spots.", "could not serialize access due to concurrent update|SQLSTATE 40001"),
		ossRule("oss-mysql-too-many-connections", model.CategoryResourceExhaustion, "MySQL", "connect", "connection-limit-exceeded", 97, "resource", "Inspect connection pooling and leaked sessions, then size max_connections from actual workload capacity.", "ERROR 1040 \\(HY000\\): Too many connections|SQLSTATE\\[08004\\].*Too many connections"),
		ossRule("oss-mysql-server-gone", model.CategoryNetworkFailure, "MySQL", "query", "server-gone-away", 97, "connectivity", "Inspect server restarts, idle/network timeouts, max packet size, and connection health before retrying.", "ERROR 2006 \\(HY000\\): MySQL server has gone away|MySQL server has gone away"),
		ossRule("oss-mysql-lock-timeout", model.CategoryConcurrencyConflict, "MySQL", "transaction", "lock-wait-timeout", 97, "concurrency", "Identify blockers and shorten transaction lock duration; retry only when the transaction is safe to repeat.", "Lock wait timeout exceeded; try restarting transaction"),
		ossRule("oss-mysql-unknown-database", model.CategoryCodeFailure, "MySQL", "connect", "database-not-found", -97, "database-config", "Create/select the intended database or correct the connection configuration.", "Unknown database ['\\\"][^'\\\"]+['\\\"]"),
		ossRule("oss-mongo-server-selection", model.CategoryNetworkFailure, "MongoDB", "connect", "server-selection-timeout", 97, "connectivity", "Verify MongoDB topology, DNS/network reachability, TLS, and replica-set discovery from the runner.", "MongoServerSelectionError:.*(?:Server selection timed out|ECONNREFUSED|connection timed out)"),
		ossRule("oss-mongo-auth-failed", model.CategoryCodeFailure, "MongoDB", "authentication", "authentication-failed", -97, "database-auth", "Correct the MongoDB credentials, authSource, mechanism, and user privileges.", "(?:MongoServerError: )?Authentication failed\\.|codeName: [\"\\']AuthenticationFailed"),
		ossRule("oss-mongo-duplicate-key", model.CategoryCodeFailure, "MongoDB", "write", "duplicate-key", -97, "deterministic", "Fix the duplicate data or uniqueness/key generation logic rather than retrying the same write unchanged.", "E11000 duplicate key error collection:"),
		ossRule("oss-redis-noauth", model.CategoryCodeFailure, "Redis", "authentication", "authentication-required", -97, "database-auth", "Configure the correct Redis credential before issuing commands.", "NOAUTH Authentication required\\."),
		ossRule("oss-redis-wrongpass", model.CategoryCodeFailure, "Redis", "authentication", "invalid-password", -97, "database-auth", "Correct the Redis ACL username/password or secret mounted into the job.", "WRONGPASS invalid username-password pair|WRONGPASS invalid username-password"),
		ossRule("oss-redis-misconf-rdb", model.CategoryResourceExhaustion, "Redis", "write", "persistence-write-disabled", 97, "resource", "Restore disk/persistence health and inspect Redis stop-writes-on-bgsave-error before resuming writes.", "MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk"),
		ossRule("oss-kafka-metadata-timeout", model.CategoryNetworkFailure, "Apache Kafka", "produce", "metadata-timeout", 97, "connectivity", "Verify broker reachability, topic existence, advertised listeners, and metadata propagation.", "TimeoutException: Topic .* not present in metadata after|KafkaTimeoutError: Failed to update metadata"),
		ossRule("oss-kafka-sasl-auth", model.CategoryCodeFailure, "Apache Kafka", "authentication", "sasl-authentication-failed", -97, "database-auth", "Correct SASL mechanism, username/password or token, and broker listener security settings.", `SaslAuthenticationException: Authentication failed|org\.apache\.kafka(?s:.*)SASL authentication failed`),
		ossRule("oss-kafka-cluster-auth", model.CategoryCodeFailure, "Apache Kafka", "authorization", "cluster-authorization-failed", -97, "database-auth", "Grant the producer/consumer identity the required Kafka ACLs for the target cluster/topic/group.", `ClusterAuthorizationException:.*not authorized|TopicAuthorizationException:|Not authorized to access topics:`),
		ossRule("oss-elasticsearch-circuit-breaker", model.CategoryResourceExhaustion, "Elasticsearch", "query", "circuit-breaker", 97, "resource", "Reduce request/aggregation memory pressure or size the cluster heap/circuit breaker from measured workload.", "circuit_breaking_exception|Data too large, data for .* would be"),
		ossRule("oss-elasticsearch-rejected-execution", model.CategoryResourceExhaustion, "Elasticsearch", "index", "thread-pool-rejected", 97, "resource", "Reduce indexing/query concurrency or increase cluster capacity after confirming thread-pool saturation.", "es_rejected_execution_exception|rejected execution of .* on EsThreadPoolExecutor"),
		ossRule("oss-elasticsearch-index-readonly", model.CategoryResourceExhaustion, "Elasticsearch", "index", "flood-stage-readonly", 97, "resource", "Free disk space and clear the read-only block only after the node falls below the flood-stage watermark.", "cluster_block_exception.*index .* blocked by: \\[TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark"),
	}
}
