package analyzer

import (
	"regexp"

	"ciradar/internal/model"
)

type Rule struct {
	ID             string
	Category       model.Category
	Provider       string
	Operation      string
	ErrorFamily    string
	Summary        string
	Recommendation string
	Weight         int
	Patterns       []*regexp.Regexp
	Excludes       []*regexp.Regexp
}

func re(s string) *regexp.Regexp { return regexp.MustCompile(`(?i)` + s) }

func BuiltinRules() []Rule {
	return []Rule{
		{ID: "npm-econnreset", Category: model.CategoryDependencyRegistry, Provider: "npm", Operation: "package-download", ErrorFamily: "connection-reset", Weight: 52, Summary: "npm package download connection was reset", Recommendation: "Avoid changing dependencies speculatively; verify npm/network health and retry after recovery.", Patterns: []*regexp.Regexp{re(`npm.*ECONNRESET|ECONNRESET.*registry\.npmjs\.org|network socket disconnected.*npm`)}},
		{ID: "npm-eai-again", Category: model.CategoryNetworkFailure, Provider: "npm", Operation: "dns-resolution", ErrorFamily: "dns-temporary-failure", Weight: 50, Summary: "Temporary DNS failure while reaching npm", Recommendation: "Check DNS/provider health; retry after connectivity recovers.", Patterns: []*regexp.Regexp{re(`EAI_AGAIN.*registry\.npmjs\.org|npm.*EAI_AGAIN`)}},
		{ID: "npm-5xx", Category: model.CategoryDependencyRegistry, Provider: "npm", Operation: "package-download", ErrorFamily: "registry-server-error", Weight: 56, Summary: "npm registry returned a server error", Recommendation: "Check npm status and avoid lockfile changes unless the failure persists after recovery.", Patterns: []*regexp.Regexp{re(`registry\.npmjs\.org.*\b(500|502|503|504)\b|npm ERR!.*\b(500|502|503|504)\b`)}},
		{ID: "npm-auth", Category: model.CategoryCodeFailure, Provider: "npm", Operation: "authentication", ErrorFamily: "authentication-failure", Weight: -28, Summary: "npm authentication or authorization failed", Recommendation: "Verify the token, package permissions, and registry configuration.", Patterns: []*regexp.Regexp{re(`npm ERR!.*(E401|E403)|Unable to authenticate.*npm|permission denied.*registry\.npmjs\.org`)}},
		{ID: "pypi-network", Category: model.CategoryDependencyRegistry, Provider: "PyPI", Operation: "package-download", ErrorFamily: "registry-connectivity", Weight: 50, Summary: "Python package download failed due to registry connectivity", Recommendation: "Check PyPI/network health and retry before modifying dependency pins.", Patterns: []*regexp.Regexp{re(`pypi\.org.*(ReadTimeout|ConnectTimeout|ConnectionError|Temporary failure|502|503|504)|pip.*Retrying.*connection`)}},
		{ID: "pypi-no-version", Category: model.CategoryCodeFailure, Provider: "PyPI", Operation: "dependency-resolution", ErrorFamily: "no-matching-distribution", Weight: -34, Summary: "No compatible Python package version was found", Recommendation: "Review package version constraints and the selected Python/platform version.", Patterns: []*regexp.Regexp{re(`No matching distribution found for|Could not find a version that satisfies the requirement`)}},
		{ID: "docker-rate-limit", Category: model.CategoryDependencyRegistry, Provider: "Docker Hub", Operation: "image-pull", ErrorFamily: "rate-limit", Weight: 46, Summary: "Container registry pull rate limit was exceeded", Recommendation: "Authenticate to the registry, use a mirror, or wait for the limit window to reset.", Patterns: []*regexp.Regexp{re(`toomanyrequests|pull rate limit|rate limit exceeded.*docker`)}},
		{ID: "docker-5xx", Category: model.CategoryDependencyRegistry, Provider: "container-registry", Operation: "image-pull", ErrorFamily: "registry-server-error", Weight: 54, Summary: "Container registry returned a server-side error", Recommendation: "Check registry health and retry after recovery.", Patterns: []*regexp.Regexp{re(`(docker\.io|ghcr\.io|registry).*\b(500|502|503|504)\b|failed to fetch anonymous token.*(502|503|504)`)}},
		{ID: "docker-manifest", Category: model.CategoryCodeFailure, Provider: "container-registry", Operation: "image-resolution", ErrorFamily: "manifest-not-found", Weight: -32, Summary: "Requested container image or manifest was not found", Recommendation: "Verify the image name, tag, architecture, and registry permissions.", Patterns: []*regexp.Regexp{re(`manifest unknown|manifest.*not found|no matching manifest for`)}},
		{ID: "apt-network", Category: model.CategoryDependencyRegistry, Provider: "APT", Operation: "package-index", ErrorFamily: "repository-connectivity", Weight: 48, Summary: "APT repository could not be reached reliably", Recommendation: "Check mirror/network health and retry before changing package configuration.", Patterns: []*regexp.Regexp{re(`Temporary failure resolving.*(ubuntu|debian)|Failed to fetch.*(502|503|504|Connection failed)|Some index files failed to download`)}},
		{ID: "apt-package-missing", Category: model.CategoryCodeFailure, Provider: "APT", Operation: "package-resolution", ErrorFamily: "package-not-found", Weight: -28, Summary: "APT package could not be located", Recommendation: "Verify repository setup, operating-system release, and package name.", Patterns: []*regexp.Regexp{re(`E: Unable to locate package|Package .* has no installation candidate`)}},
		{ID: "github-runner-lost", Category: model.CategoryRunnerFailure, Provider: "GitHub Actions", Operation: "runner-communication", ErrorFamily: "runner-lost", Weight: 62, Summary: "GitHub Actions lost communication with the runner", Recommendation: "Treat this as runner/infrastructure failure; retry on a fresh runner.", Patterns: []*regexp.Regexp{re(`Lost communication with the server|The runner has received a shutdown signal|runner.*(disconnected|lost communication)|The self-hosted runner.*lost`)}},
		{ID: "github-runner-not-found", Category: model.CategoryRunnerFailure, Provider: "GitHub Actions", Operation: "runner-allocation", ErrorFamily: "runner-not-found", Weight: 58, Summary: "A suitable runner could not be allocated", Recommendation: "Check runner labels/capacity and GitHub Actions service health.", Patterns: []*regexp.Regexp{re(`Runner not found|No runner matching the specified labels|Waiting for a runner to pick up this job`)}},
		{ID: "github-cancelled", Category: model.CategoryUnknown, Provider: "GitHub Actions", Operation: "job-execution", ErrorFamily: "task-cancelled", Weight: 18, Summary: "The task was cancelled without a specific root cause", Recommendation: "Inspect timeout, concurrency cancellation, runner shutdown, and upstream workflow conditions.", Patterns: []*regexp.Regexp{re(`The operation was canceled|A task was cancelled|The job was canceled|The operation was cancelled`)}},
		{ID: "github-cache", Category: model.CategoryCacheFailure, Provider: "GitHub Actions Cache", Operation: "cache-restore", ErrorFamily: "cache-service-failure", Weight: 45, Summary: "GitHub Actions cache restore/save failed", Recommendation: "Continue without cache when possible and retry after cache service recovery.", Patterns: []*regexp.Regexp{re(`Failed to restore cache|Cache service responded with.*(500|502|503|504)|Unable to reserve cache|Failed to save cache`)}},
		{ID: "timeout-network", Category: model.CategoryNetworkFailure, Provider: "network", Operation: "remote-request", ErrorFamily: "timeout", Weight: 40, Summary: "A remote network operation timed out", Recommendation: "Check the named external provider and retry with bounded backoff.", Patterns: []*regexp.Regexp{re(`i/o timeout|TLS handshake timeout|context deadline exceeded.*(http|download|connect)|connection timed out|ETIMEDOUT`)}},
		{ID: "dns-failure", Category: model.CategoryNetworkFailure, Provider: "DNS", Operation: "name-resolution", ErrorFamily: "dns-failure", Weight: 48, Summary: "DNS name resolution failed", Recommendation: "Verify DNS and provider availability before changing project code.", Patterns: []*regexp.Regexp{re(`Temporary failure in name resolution|no such host|Name or service not known|Could not resolve host`)}},
		{ID: "tls-failure", Category: model.CategoryNetworkFailure, Provider: "network", Operation: "tls", ErrorFamily: "tls-failure", Weight: 36, Summary: "TLS negotiation or certificate validation failed", Recommendation: "Check certificate validity, system clock, proxy interception, and provider health.", Patterns: []*regexp.Regexp{re(`x509: certificate|certificate verify failed|SSL certificate problem|remote error: tls|TLS handshake`)}},
		{ID: "disk-full", Category: model.CategoryResourceExhaustion, Provider: "runner", Operation: "filesystem", ErrorFamily: "disk-full", Weight: 55, Summary: "Runner disk space was exhausted", Recommendation: "Clean build artifacts/caches or use a runner with more disk capacity.", Patterns: []*regexp.Regexp{re(`no space left on device|ENOSPC|disk quota exceeded`)}},
		{ID: "oom", Category: model.CategoryResourceExhaustion, Provider: "runner", Operation: "memory", ErrorFamily: "out-of-memory", Weight: 52, Summary: "The job exceeded available memory", Recommendation: "Reduce concurrency/memory usage or use a larger runner.", Patterns: []*regexp.Regexp{re(`Out of memory|Killed process .* out of memory|fatal error: runtime: out of memory|Java heap space|exit code 137`)}},
		{ID: "compiler-go", Category: model.CategoryCodeFailure, Provider: "compiler", Operation: "compile", ErrorFamily: "go-compile-error", Weight: -45, Summary: "Go compilation failed deterministically", Recommendation: "Fix the reported source or type error.", Patterns: []*regexp.Regexp{re(`\.go:\d+:\d+: (undefined|cannot use|syntax error|too many arguments|not enough arguments)|build failed.*go`)}, Excludes: []*regexp.Regexp{re(`proxy\.golang\.org.*(timeout|502|503|504)`)}},
		{ID: "compiler-ts", Category: model.CategoryCodeFailure, Provider: "compiler", Operation: "compile", ErrorFamily: "typescript-compile-error", Weight: -44, Summary: "TypeScript compilation failed deterministically", Recommendation: "Fix the reported TypeScript source/type error.", Patterns: []*regexp.Regexp{re(`error TS\d{4}:|TypeScript error in`)}},
		{ID: "compiler-rust", Category: model.CategoryCodeFailure, Provider: "compiler", Operation: "compile", ErrorFamily: "rust-compile-error", Weight: -44, Summary: "Rust compilation failed deterministically", Recommendation: "Fix the reported Rust compiler error.", Patterns: []*regexp.Regexp{re(`error\[E\d{4}\]:|could not compile .* due to`)}},
		{ID: "test-assertion", Category: model.CategoryCodeFailure, Provider: "test-runner", Operation: "test", ErrorFamily: "assertion-failure", Weight: -38, Summary: "A deterministic test assertion failed", Recommendation: "Inspect the failing assertion and changes affecting the tested behavior.", Patterns: []*regexp.Regexp{re(`AssertionError|expected .* (to equal|but got)|FAIL: Test|Tests:.*failed`)}, Excludes: []*regexp.Regexp{re(`timeout|ECONNRESET|EAI_AGAIN|connection refused`)}},
		{ID: "test-flake-retry", Category: model.CategoryTestFlake, Provider: "test-runner", Operation: "test", ErrorFamily: "flaky-retry", Weight: 25, Summary: "Test behavior indicates a possible flake", Recommendation: "Rerun the isolated test and inspect timing, ordering, network, or shared-state dependencies.", Patterns: []*regexp.Regexp{re(`flaky test|passed on retry|retrying failed test|test.*intermittent`)}},
	}
}
