package analyzer

import (
	"regexp"

	"ciradar/internal/model"
)

type Rule struct {
	ID             string
	Category       model.Category
	Provider       string
	Operation      string
	ErrorFamily    string
	Summary        string
	Recommendation string
	Weight         int
	SignalGroup    string
	Patterns       []*regexp.Regexp
	Excludes       []*regexp.Regexp
}

func re(s string) *regexp.Regexp { return regexp.MustCompile(`(?i)` + s) }

func BuiltinRules() []Rule {
	return []Rule{

		{ID: "browser-no-display", Category: model.CategoryCodeFailure, Provider: "Browser test runner", Operation: "browser-launch", ErrorFamily: "display-server-missing", Weight: -58, SignalGroup: "deterministic", Summary: "A headed browser was launched without an available display server", Recommendation: "Run headless or start the job under Xvfb and verify the display configuration.", Patterns: []*regexp.Regexp{re(`headed browser without having (an? )?XServer|use ['\"]?xvfb-run|DISPLAY.*X11 server.*not working`)}},
		{ID: "browser-test-timeout", Category: model.CategoryTestFlake, Provider: "Browser test runner", Operation: "test-execution", ErrorFamily: "browser-test-timeout", Weight: 38, SignalGroup: "test-flake", Summary: "A browser test or navigation exceeded its timeout", Recommendation: "Retry once, then inspect deterministic waits, page readiness, and runner load if it repeats.", Patterns: []*regexp.Regexp{re(`page\.(goto|waitFor|click).*Test timeout of \d+ms exceeded|The action .* has timed out after \d+ minutes|cy\.(then|visit|get).*timed out after \d+ms`)}},
		{ID: "browser-target-closed", Category: model.CategoryTestFlake, Provider: "Browser test runner", Operation: "browser-session", ErrorFamily: "browser-target-closed", Weight: 36, SignalGroup: "test-flake", Summary: "The browser page, context, or process closed unexpectedly", Recommendation: "Retry once and inspect browser crash logs, lifecycle handling, and runner resources if it recurs.", Patterns: []*regexp.Regexp{re(`Target(page|ClosedException| page, context or browser) has been closed|Target page, context or browser has been closed|browserContext\.close: Target page`)}},
		{ID: "browser-worker-force-killed", Category: model.CategoryTestFlake, Provider: "Browser test runner", Operation: "worker-teardown", ErrorFamily: "worker-force-killed", Weight: 46, SignalGroup: "test-flake", Summary: "A browser-test worker did not exit and was force-killed", Recommendation: "Inspect fixture teardown and browser-process cleanup; retry once if the hang is intermittent.", Patterns: []*regexp.Regexp{re(`worker-\d+ process did not exit within \d+ms after stop, force-killed|chrome-headless-shell.*doesn'?t exit|worker.*force-killed`)}},
		{ID: "cypress-tab-closed", Category: model.CategoryTestFlake, Provider: "Cypress", Operation: "browser-session", ErrorFamily: "test-tab-closed", Weight: 44, SignalGroup: "test-flake", Summary: "The Cypress test tab closed unexpectedly", Recommendation: "Retry once and inspect Electron/browser crash logs and runner resources if it recurs.", Patterns: []*regexp.Regexp{re(`electron tab running Cypress tests closed unexpectedly|failed the current spec and aborted the run.*tab.*closed`)}},
		{ID: "cypress-permission", Category: model.CategoryCodeFailure, Provider: "Cypress", Operation: "local-state", ErrorFamily: "filesystem-permission", Weight: -54, SignalGroup: "deterministic", Summary: "Cypress cannot write its required local state", Recommendation: "Grant the runner write access to the Cypress cache/state directory or relocate it.", Patterns: []*regexp.Regexp{re(`EACCES: permission denied, (open|unlink).*Cypress.*binary_state\.json`)}},
		{ID: "invalid-machine-instruction", Category: model.CategoryCodeFailure, Provider: "Native binary", Operation: "process-start", ErrorFamily: "invalid-machine-instruction", Weight: -48, SignalGroup: "deterministic", Summary: "A native executable used an unsupported machine instruction", Recommendation: "Use a binary compatible with the runner architecture and CPU, and verify required native libraries.", Patterns: []*regexp.Regexp{re(`killed with SIGILL|Invalid machine instruction|illegal instruction.*core dumped`)}},

		{ID: "git-lfs-proxy-auth", Category: model.CategoryCodeFailure, Provider: "Git LFS", Operation: "proxy-authentication", ErrorFamily: "proxy-authentication-required", Weight: -54, SignalGroup: "deterministic", Summary: "Git LFS proxy authentication failed", Recommendation: "Correct the proxy URL and credentials used by Git LFS.", Patterns: []*regexp.Regexp{re(`git-lfs.*Proxy authentication required|batch response:.*Proxy authentication required`)}},
		{ID: "git-lfs-malformed-url", Category: model.CategoryCodeFailure, Provider: "Git LFS", Operation: "configuration", ErrorFamily: "malformed-lfs-url", Weight: -58, SignalGroup: "deterministic", Summary: "The configured Git LFS URL is malformed", Recommendation: "Correct the LFS endpoint or remote URL, including its protocol separator.", Patterns: []*regexp.Regexp{re(`batch request: missing protocol|Endpoint=https:[^/]`)}},
		{ID: "git-lfs-client-cert", Category: model.CategoryCodeFailure, Provider: "Git LFS", Operation: "tls-configuration", ErrorFamily: "client-certificate-missing", Weight: -56, SignalGroup: "deterministic", Summary: "A configured Git LFS client certificate file is missing", Recommendation: "Correct or remove the scoped client-certificate configuration.", Patterns: []*regexp.Regexp{re(`Error reading client cert file.*no such file or directory`)}},
		{ID: "git-lfs-transport-eof", Category: model.CategoryNetworkFailure, Provider: "Git LFS", Operation: "remote-request", ErrorFamily: "transport-eof", Weight: 46, SignalGroup: "connectivity", Summary: "A Git LFS remote request ended unexpectedly", Recommendation: "Check the remote LFS service and network path, then retry with bounded backoff.", Patterns: []*regexp.Regexp{re(`git-lfs.*(locks/verify|objects/batch).*EOF|Post .*info/lfs/locks/verify.*EOF|pure SSH protocol connection failed.*EOF`)}},
		{ID: "git-lfs-ssh-unavailable", Category: model.CategoryNetworkFailure, Provider: "Git LFS", Operation: "ssh-transfer", ErrorFamily: "ssh-connection-unavailable", Weight: 48, SignalGroup: "connectivity", Summary: "The Git LFS SSH transfer connection was unavailable", Recommendation: "Verify SSH transfer support and connectivity, then retry with bounded backoff.", Patterns: []*regexp.Regexp{re(`pure SSH connection unavailable|Failed to connect to remote SSH server`)}},
		{ID: "git-lfs-auth", Category: model.CategoryCodeFailure, Provider: "Git LFS", Operation: "authentication", ErrorFamily: "lfs-authentication-failure", Weight: -54, SignalGroup: "deterministic", Summary: "Git LFS authentication or lock verification was rejected", Recommendation: "Refresh credentials and verify repository/LFS permissions and lock settings.", Patterns: []*regexp.Regexp{re(`Authentication required: Authorization error:.*info/lfs|must have push access to verify locks|error getting verify links: Authentication error`)}},
		{ID: "git-lfs-repository-release-missing", Category: model.CategoryCodeFailure, Provider: "Git LFS package repository", Operation: "package-repository", ErrorFamily: "distribution-not-supported", Weight: -46, SignalGroup: "deterministic", Summary: "The configured Git LFS package repository does not support this distribution", Recommendation: "Use a supported repository distribution or install Git LFS through another supported channel.", Patterns: []*regexp.Regexp{re(`packagecloud\.io/github/git-lfs.*404 Not Found|repository .*git-lfs.* does not have a Release file`)}},
		{ID: "package-repository-signature-policy", Category: model.CategoryDependencyRegistry, Provider: "Package repository", Operation: "metadata-verification", ErrorFamily: "repository-signature-rejected", Weight: 52, SignalGroup: "registry", Summary: "A package repository signature was rejected by the current security policy", Recommendation: "Check the repository maintainer's signing-key update before weakening local signature policy.", Patterns: []*regexp.Regexp{re(`OpenPGP signature verification failed.*packagecloud|Policy rejected.*SHA1|repository .* is not signed.*packagecloud`)}},
		{ID: "npm-econnreset", Category: model.CategoryDependencyRegistry, Provider: "npm", Operation: "package-download", ErrorFamily: "connection-reset", Weight: 52, SignalGroup: "connectivity", Summary: "npm package download connection was reset", Recommendation: "Avoid changing dependencies speculatively; verify npm/network health and retry after recovery.", Patterns: []*regexp.Regexp{re(`npm.*ECONNRESET|ECONNRESET.*registry\.npmjs\.org|network socket disconnected.*npm`)}},
		{ID: "npm-eai-again", Category: model.CategoryNetworkFailure, Provider: "npm", Operation: "dns-resolution", ErrorFamily: "dns-temporary-failure", Weight: 50, SignalGroup: "connectivity", Summary: "Temporary DNS failure while reaching npm", Recommendation: "Check DNS/provider health; retry after connectivity recovers.", Patterns: []*regexp.Regexp{re(`EAI_AGAIN.*registry\.npmjs\.org|npm.*EAI_AGAIN`)}},
		{ID: "npm-5xx", Category: model.CategoryDependencyRegistry, Provider: "npm", Operation: "package-download", ErrorFamily: "registry-server-error", Weight: 56, SignalGroup: "connectivity", Summary: "npm registry returned a server error", Recommendation: "Check npm status and avoid lockfile changes unless the failure persists after recovery.", Patterns: []*regexp.Regexp{re(`registry\.npmjs\.org.*\b(500|502|503|504)\b|npm ERR!.*\b(500|502|503|504)\b`)}},
		{ID: "npm-auth", Category: model.CategoryCodeFailure, Provider: "npm", Operation: "authentication", ErrorFamily: "authentication-failure", Weight: -36, SignalGroup: "deterministic", Summary: "npm authentication or authorization failed", Recommendation: "Verify the token, package permissions, and registry configuration.", Patterns: []*regexp.Regexp{re(`npm ERR!.*(E401|E403)|Unable to authenticate.*npm|permission denied.*registry\.npmjs\.org`)}},
		{ID: "npm-corrupt-archive", Category: model.CategoryCacheFailure, Provider: "npm", Operation: "package-unpack", ErrorFamily: "corrupt-archive", Weight: 42, SignalGroup: "cache", Summary: "npm received or cached a corrupt package archive", Recommendation: "Clear the affected npm cache entry and retry; investigate proxies or registries if it recurs.", Patterns: []*regexp.Regexp{re(`TAR_BAD_ARCHIVE|Unrecognized archive format`)}},

		{ID: "pypi-tls", Category: model.CategoryNetworkFailure, Provider: "PyPI", Operation: "tls", ErrorFamily: "certificate-validation", Weight: 58, SignalGroup: "connectivity", Summary: "TLS certificate validation failed while reaching PyPI", Recommendation: "Check the system trust store, proxy interception, and system clock before changing dependencies.", Patterns: []*regexp.Regexp{re(`pypi\.org.*(CERTIFICATE_VERIFY_FAILED|SSLCertVerificationError|certificate verify failed)|Could not fetch URL.*pypi\.org.*ssl certificate`)}},
		{ID: "pypi-network", Category: model.CategoryDependencyRegistry, Provider: "PyPI", Operation: "package-download", ErrorFamily: "registry-connectivity", Weight: 54, SignalGroup: "connectivity", Summary: "Python package download failed due to registry connectivity", Recommendation: "Check PyPI, DNS, proxy, and network health before modifying dependency pins.", Patterns: []*regexp.Regexp{re(`pypi\.org.*(ReadTimeout|ConnectTimeout|ConnectionError|NameResolutionError|ProxyError|Temporary failure|Failed to resolve|Cannot connect to proxy|502|503|504)|pip.*Retrying.*(connection|NameResolutionError|ProxyError)|Could not fetch URL.*pypi\.org.*(connection|timed out|resolve)`)}},
		{ID: "pypi-resolution-impossible", Category: model.CategoryCodeFailure, Provider: "PyPI", Operation: "dependency-resolution", ErrorFamily: "dependency-conflict", Weight: -48, SignalGroup: "deterministic", Summary: "Python dependency constraints are mutually incompatible", Recommendation: "Review conflicting version constraints and pin a compatible dependency set.", Patterns: []*regexp.Regexp{re(`ResolutionImpossible|package versions have conflicting dependencies|Cannot install .* because these package versions have conflicting dependencies`)}},
		{ID: "pypi-auth-prompt", Category: model.CategoryCodeFailure, Provider: "PyPI", Operation: "authentication", ErrorFamily: "noninteractive-authentication", Weight: -46, SignalGroup: "deterministic", Summary: "Python package authentication failed in a non-interactive process", Recommendation: "Configure index credentials non-interactively with a scoped secret or supported keyring.", Patterns: []*regexp.Regexp{re(`User for .*ERROR: Exception|EOFError: EOF when reading a line`)}},
		{ID: "pypi-externally-managed", Category: model.CategoryCodeFailure, Provider: "Python", Operation: "environment", ErrorFamily: "externally-managed-environment", Weight: -48, SignalGroup: "deterministic", Summary: "The Python environment rejects direct package installation", Recommendation: "Use a virtual environment or the operating system package manager.", Patterns: []*regexp.Regexp{re(`externally-managed-environment|environment is externally managed`)}},
		{ID: "pypi-inconsistent-version", Category: model.CategoryCodeFailure, Provider: "PyPI", Operation: "package-metadata", ErrorFamily: "inconsistent-version", Weight: -46, SignalGroup: "deterministic", Summary: "Package filename and metadata versions are inconsistent", Recommendation: "Use a corrected package release or adjust the package build metadata.", Patterns: []*regexp.Regexp{re(`has inconsistent version: filename has .* but metadata has`)}},
		{ID: "pip-install-environment", Category: model.CategoryCodeFailure, Provider: "Python", Operation: "package-install", ErrorFamily: "local-environment-error", Weight: -42, SignalGroup: "deterministic", Summary: "Python package installation failed in the local runner environment", Recommendation: "Inspect the reported filesystem path, permissions, and Python installation state.", Patterns: []*regexp.Regexp{re(`Could not install packages due to an EnvironmentError|Failed to write executable|\[WinError 2\].*system cannot find the file`)}},
		{ID: "pypi-no-version", Category: model.CategoryCodeFailure, Provider: "PyPI", Operation: "dependency-resolution", ErrorFamily: "no-matching-distribution", Weight: -38, SignalGroup: "deterministic", Summary: "No compatible Python package version was found", Recommendation: "Review package version constraints and the selected Python/platform version.", Patterns: []*regexp.Regexp{re(`No matching distribution found for|Could not find a version that satisfies the requirement`)}, Excludes: []*regexp.Regexp{re(`NameResolutionError|ProxyError|Cannot connect to proxy|CERTIFICATE_VERIFY_FAILED|SSLCertVerificationError|certificate verify failed|Failed to resolve|Could not resolve host|Temporary failure in name resolution|Could not fetch URL.*(certificate|connect|resolve)|Retrying.*connection|EOFError: EOF when reading a line`)}},

		{ID: "go-module-service", Category: model.CategoryDependencyRegistry, Provider: "Go module services", Operation: "module-verification", ErrorFamily: "module-service-failure", Weight: 54, SignalGroup: "connectivity", Summary: "A Go module proxy or checksum service failed", Recommendation: "Check proxy.golang.org or sum.golang.org health and retry before changing go.mod or go.sum.", Patterns: []*regexp.Regexp{re(`(proxy|sum)\.golang\.org.*(500|502|503|504|Internal Server Error|unexpected EOF|:\s*EOF)`)}},
		{ID: "git-network", Category: model.CategoryNetworkFailure, Provider: "Git", Operation: "repository-fetch", ErrorFamily: "git-network-failure", Weight: 46, SignalGroup: "connectivity", Summary: "Git repository transfer failed due to a network or remote service error", Recommendation: "Check the remote host and retry with bounded backoff before changing repository configuration.", Patterns: []*regexp.Regexp{re(`RPC failed; HTTP 5\d\d|remote: Internal Server Error|unexpected disconnect while reading sideband packet|fatal: early EOF|GnuTLS recv error|TLS connection was non-properly terminated|Empty reply from server`)}},
		{ID: "git-repository-not-found", Category: model.CategoryCodeFailure, Provider: "Git", Operation: "repository-fetch", ErrorFamily: "repository-not-found", Weight: -42, SignalGroup: "deterministic", Summary: "The configured Git repository was not found or is inaccessible", Recommendation: "Verify the repository URL, credentials, and access permissions.", Patterns: []*regexp.Regexp{re(`remote: Repository not found|fatal: repository .* not found|Could not read from remote repository`)}, Excludes: []*regexp.Regexp{re(`Could not resolve host|Could not resolve hostname|Connection refused|timed out`)}},
		{ID: "ci-auth-token", Category: model.CategoryCodeFailure, Provider: "CI credentials", Operation: "authentication", ErrorFamily: "invalid-token", Weight: -48, SignalGroup: "deterministic", Summary: "A CI service credential or access token was rejected", Recommendation: "Rotate or correct the scoped secret and verify its permissions.", Patterns: []*regexp.Regexp{re(`code = Unauthenticated.*(bad access token|invalid token)|oauth: bad access token|authentication failed.*token`)}},
		{ID: "tls-policy", Category: model.CategoryCodeFailure, Provider: "TLS configuration", Operation: "tls", ErrorFamily: "tls-policy-rejection", Weight: -40, SignalGroup: "deterministic", Summary: "TLS negotiation was rejected by a security policy or incompatible configuration", Recommendation: "Review TLS versions, cipher suites, certificate policy, and the target service configuration.", Patterns: []*regexp.Regexp{re(`tls: insufficient security level|no cipher suite supported|protocol version not supported`)}},
		{ID: "openssl-transport-failure", Category: model.CategoryNetworkFailure, Provider: "TLS transport", Operation: "tls", ErrorFamily: "ssl-syscall-failure", Weight: 52, SignalGroup: "connectivity", Summary: "An SSL/TLS connection ended at the transport layer", Recommendation: "Check the target endpoint, IPv4/IPv6 routing, proxy, and TLS service health before changing project code.", Patterns: []*regexp.Regexp{re(`SSL_ERROR_SYSCALL|OpenSSL SSL_connect:.*(?:connection|:443)|unexpected eof while reading.*SSL`)}},
		{ID: "x509-test-expectation", Category: model.CategoryCodeFailure, Provider: "test-runner", Operation: "test", ErrorFamily: "certificate-test-failure", Weight: -40, SignalGroup: "deterministic", Summary: "A certificate validation test produced an unexpected deterministic result", Recommendation: "Inspect the test fixture, trust anchors, and expected certificate chain behavior.", Patterns: []*regexp.Regexp{re(`expected result:.*actual result: x509:|expected success, built chain with error: x509:`)}},
		{ID: "go-test-assertion", Category: model.CategoryCodeFailure, Provider: "Go test", Operation: "test-assertion", ErrorFamily: "assertion-failure", Weight: -62, SignalGroup: "deterministic", Summary: "A Go test failed a deterministic assertion", Recommendation: "Inspect the first failing test location and correct the implementation or expected value before rerunning the suite.", Patterns: []*regexp.Regexp{re(`(?ms)^--- FAIL: Test[^\r\n]*(?s:.*?)(?:expected(?:\s+value)?\s*[:=].*?actual\s*[:=]|expected.*?(?:got|but got)|got\s*[:=]?.*?want\s*[:=]?|want\s*[:=]?.*?got\s*[:=]?|assert(?:ion)? failed|not equal|Error Trace:.*?Error:.*?(?:Not equal|Should be true|Should be false)|Diff:.*?--- Expected.*?\+\+\+ Actual)`)}},
		{ID: "go-test-panic", Category: model.CategoryCodeFailure, Provider: "Go test", Operation: "test-panic", ErrorFamily: "test-panic", Weight: -64, SignalGroup: "deterministic", Summary: "A Go test panicked during execution", Recommendation: "Inspect the panic stack and fix the failing test or implementation before rerunning the suite.", Patterns: []*regexp.Regexp{re(`(?ms)^--- FAIL: Test[^\r\n]*(?s:.*?)(?:panic: \[recovered\]|panic: runtime error|panic: [^\r\n]+)`)}, Excludes: []*regexp.Regexp{re(`panic: test timed out`)}},
		{ID: "go-test-failure", Category: model.CategoryCodeFailure, Provider: "Go test", Operation: "test-execution", ErrorFamily: "test-failure", Weight: -48, SignalGroup: "deterministic", Summary: "A Go test failed deterministically", Recommendation: "Inspect the first file and line emitted under the failing test and reproduce that test locally.", Patterns: []*regexp.Regexp{re(`(?m)^--- FAIL: Test[^\r\n]*`)}, Excludes: []*regexp.Regexp{re(`panic: test timed out|test timeout|context deadline exceeded`)}},
		{ID: "test-timeout-flake", Category: model.CategoryTestFlake, Provider: "test-runner", Operation: "test", ErrorFamily: "test-timeout", Weight: 30, SignalGroup: "flake", Summary: "A test timed out or hung and may be flaky", Recommendation: "Rerun the isolated test and inspect timing, synchronization, and shared-state dependencies.", Patterns: []*regexp.Regexp{re(`panic: test timed out|test timed out while running command|timeout exceeded:.*\(.*s\)|timeout in .*reconnect|timeout waiting for .*log|likely due to hang`)}},
		{ID: "local-test-transport-flake", Category: model.CategoryTestFlake, Provider: "test-runner", Operation: "test", ErrorFamily: "local-transport-flake", Weight: 28, SignalGroup: "flake", Summary: "A test failed on a local transport or closed-pipe timing condition", Recommendation: "Rerun the isolated test and inspect synchronization, cleanup, and local socket lifecycle.", Patterns: []*regexp.Regexp{re(`127\.0\.0\.1.*(use of closed network connection|Client\.Timeout exceeded|i/o timeout)|read/write on closed pipe`)}},

		{ID: "nuget-registry-transient", Category: model.CategoryDependencyRegistry, Provider: "NuGet", Operation: "package-restore", ErrorFamily: "registry-transient-error", Weight: 58, SignalGroup: "connectivity", Summary: "A NuGet feed returned a transient rate-limit or server error", Recommendation: "Check the affected feed and retry with bounded backoff before changing package references.", Patterns: []*regexp.Regexp{re(`(?:NU1301|NU1900|Unable to load the service index)(?s:.*?)(?:429\s*\(Too Many Requests\)|5(?:00|02|03|04)\s*\((?:Internal Server Error|Bad Gateway|Service Unavailable|Gateway Timeout)\))`)}, Excludes: []*regexp.Regexp{re(`localhost|127\.0\.0\.1|proxy|connection refused|actively refused|could not be resolved|Name or service not known`)}},
		{ID: "nuget-network", Category: model.CategoryNetworkFailure, Provider: "NuGet", Operation: "package-restore", ErrorFamily: "feed-connectivity", Weight: 54, SignalGroup: "connectivity", Summary: "NuGet could not reach the configured package feed", Recommendation: "Check DNS, proxy, local feed availability, and network routing before changing package references.", Patterns: []*regexp.Regexp{re(`(?:NU1301|Unable to load the service index)(?s:.*?)(?:actively refused|connection refused|proxy tunnel|proxy.*(?:502|timed out|no response)|remote name could not be resolved|Name or service not known)`)}},
		{ID: "nuget-package-not-found", Category: model.CategoryCodeFailure, Provider: "NuGet", Operation: "dependency-resolution", ErrorFamily: "package-not-found", Weight: -58, SignalGroup: "deterministic", Summary: "NuGet could not find the requested package in the configured sources", Recommendation: "Verify the package ID/version, source mapping, credentials, and enabled feeds.", Patterns: []*regexp.Regexp{re(`NU1101:.*Unable to find package|No packages exist with this id in source`)}},
		{ID: "nuget-source-invalid", Category: model.CategoryCodeFailure, Provider: "NuGet", Operation: "source-configuration", ErrorFamily: "invalid-package-source", Weight: -56, SignalGroup: "deterministic", Summary: "A configured NuGet package source is invalid or missing", Recommendation: "Correct or remove the package source path/URL and verify source mapping.", Patterns: []*regexp.Regexp{re(`NU5000:.*Invalid package source|Invalid package source path|NU1301(?s:.*?)(?:404\s*\(Not Found\)|does not contain a valid package source)`)}},
		{ID: "nuget-signature-policy", Category: model.CategoryCodeFailure, Provider: "NuGet", Operation: "signature-validation", ErrorFamily: "signature-trust-failure", Weight: -56, SignalGroup: "deterministic", Summary: "NuGet rejected a package or repository signature because its trust chain or policy is invalid", Recommendation: "Review trusted roots, repository signing policy, package signature, and system clock.", Patterns: []*regexp.Regexp{re(`NU(?:3018|3028):|Package signature validation failed|repository primary signature is invalid|UntrustedRoot.*certificate`)}},

		{ID: "docker-rate-limit", Category: model.CategoryDependencyRegistry, Provider: "Docker Hub", Operation: "image-pull", ErrorFamily: "rate-limit", Weight: 46, SignalGroup: "connectivity", Summary: "Container registry pull rate limit was exceeded", Recommendation: "Authenticate to the registry, use a mirror, or wait for the limit window to reset.", Patterns: []*regexp.Regexp{re(`toomanyrequests|pull rate limit|rate limit exceeded.*docker`)}},
		{ID: "docker-5xx", Category: model.CategoryDependencyRegistry, Provider: "container-registry", Operation: "image-pull", ErrorFamily: "registry-server-error", Weight: 54, SignalGroup: "connectivity", Summary: "Container registry returned a server-side error", Recommendation: "Check registry health and retry after recovery.", Patterns: []*regexp.Regexp{re(`(docker\.io|ghcr\.io|registry).*\b(500|502|503|504)\b|failed to fetch anonymous token.*(502|503|504)`)}},
		{ID: "container-malformed-reference", Category: model.CategoryCodeFailure, Provider: "container configuration", Operation: "image-resolution", ErrorFamily: "malformed-image-reference", Weight: -72, SignalGroup: "deterministic", Summary: "The rendered container image reference appears malformed or contains a nested registry hostname", Recommendation: "Inspect chart/template values and render the final image reference before retrying authentication.", Patterns: []*regexp.Regexp{re(`(?:image|reference|pull image)[^\n]*(?:ghcr\.io|docker\.io|gcr\.io|quay\.io|amazonaws\.com)/[^\s"]*(?:ghcr\.io|docker\.io|gcr\.io|quay\.io|amazonaws\.com)`)}},
		{ID: "container-image-not-found", Category: model.CategoryCodeFailure, Provider: "container-registry", Operation: "image-resolution", ErrorFamily: "image-not-found", Weight: -68, SignalGroup: "deterministic", Summary: "The requested container image or tag does not exist", Recommendation: "Correct the image repository/tag or publish the missing image; retries alone will not fix a nonexistent reference.", Patterns: []*regexp.Regexp{re(`(?:Failed to pull image|ErrImagePull|ImagePullBackOff|failed to resolve (?:image|reference))(?s:.*?)(?:code = NotFound|:\s*not found|manifest unknown)|failed to pull and unpack image(?s:.*?)(?:code = NotFound|:\s*not found)|(?:docker\.io|gcr\.io|ghcr\.io|quay\.io)/[^\s"]+:.*:\s*not found`)}, Excludes: []*regexp.Regexp{re(`TLS handshake timeout|connection reset|Could not resolve host|i/o timeout|502|503|504`)}},
		{ID: "docker-manifest", Category: model.CategoryCodeFailure, Provider: "container-registry", Operation: "image-resolution", ErrorFamily: "manifest-not-found", Weight: -54, SignalGroup: "deterministic", Summary: "Requested container image or manifest was not found", Recommendation: "Verify the image name, tag, architecture, and registry permissions.", Patterns: []*regexp.Regexp{re(`manifest unknown|manifest.*not found|no matching manifest for`)}},
		{ID: "container-pull-eof", Category: model.CategoryDependencyRegistry, Provider: "container-registry", Operation: "image-pull", ErrorFamily: "truncated-registry-transfer", Weight: 54, SignalGroup: "connectivity", Summary: "A container registry transfer ended unexpectedly", Recommendation: "Retry with bounded backoff and check registry/CDN health before changing the image reference.", Patterns: []*regexp.Regexp{re(`(?:docker|image|layer|pull|registry|endpoint)(?s:.*?)(?:unexpected EOF|Download failed.*EOF)|Attempting next endpoint for pull after error: unexpected EOF`)}},
		{ID: "container-auth", Category: model.CategoryCodeFailure, Provider: "container-registry", Operation: "authentication", ErrorFamily: "missing-registry-credentials", Weight: -56, SignalGroup: "deterministic", Summary: "Container registry credentials are missing or invalid", Recommendation: "Configure docker login/credential helpers and verify registry permissions.", Patterns: []*regexp.Regexp{re(`no basic auth credentials|unauthorized: authentication required|denied: requested access to the resource is denied`)}},
		{ID: "container-manifest-capability", Category: model.CategoryCodeFailure, Provider: "container-toolchain", Operation: "manifest-processing", ErrorFamily: "unsupported-or-invalid-manifest", Weight: -54, SignalGroup: "deterministic", Summary: "The container toolchain cannot process or export the requested manifest format", Recommendation: "Use a supported exporter/client version and verify whether the reference is an image or manifest list.", Patterns: []*regexp.Regexp{re(`does not currently support exporting manifest lists|Schema 2 manifest not supported by client| is a manifest list|exporter does not support.*manifest`)}},

		{ID: "composer-transfer-partial", Category: model.CategoryNetworkFailure, Provider: "Composer", Operation: "package-download", ErrorFamily: "partial-transfer", Weight: 50, SignalGroup: "connectivity", Summary: "Composer received an incomplete package transfer", Recommendation: "Retry the transfer and check the proxy, CDN, or remote host before changing dependency constraints.", Patterns: []*regexp.Regexp{re(`curl error 18|Transferred a partial file`)}},
		{ID: "composer-platform-requirement", Category: model.CategoryCodeFailure, Provider: "Composer", Operation: "platform-validation", ErrorFamily: "missing-or-incompatible-platform", Weight: -62, SignalGroup: "deterministic", Summary: "Composer rejected the local PHP platform or a required extension", Recommendation: "Install or enable the required PHP extension, or use a compatible PHP platform configuration.", Patterns: []*regexp.Regexp{re(`requires PHP extension .* but it is missing from your system|requires php .* your php version .* does not satisfy|lock file does not contain a compatible set of packages`)}},
		{ID: "composer-security-policy", Category: model.CategoryCodeFailure, Provider: "Composer", Operation: "dependency-policy", ErrorFamily: "security-advisory-block", Weight: -60, SignalGroup: "deterministic", Summary: "Composer security policy blocked one or more dependency versions", Recommendation: "Update the affected dependency or explicitly review and configure the advisory policy; do not treat this as a provider outage.", Patterns: []*regexp.Regexp{re(`not loaded, because they are affected by security advisories|block-insecure.*false|audit "ignore" config`)}},
		{ID: "composer-repository-priority", Category: model.CategoryCodeFailure, Provider: "Composer", Operation: "repository-resolution", ErrorFamily: "repository-priority-conflict", Weight: -59, SignalGroup: "deterministic", Summary: "Composer repository priority or canonical-source rules rejected the requested package", Recommendation: "Review repository order, canonical flags, and the requested branch or version constraint.", Patterns: []*regexp.Regexp{re(`higher repository priority|repository is canonical.*lower priority|lower priority repo.*not installable`)}},
		{ID: "composer-dependency-resolution", Category: model.CategoryCodeFailure, Provider: "Composer", Operation: "dependency-resolution", ErrorFamily: "dependency-constraint-conflict", Weight: -56, SignalGroup: "deterministic", Summary: "Composer could not satisfy the declared dependency constraints", Recommendation: "Review the root and transitive version constraints, lockfile state, and package availability.", Patterns: []*regexp.Regexp{re(`Your requirements could not be resolved to an installable set of packages(?s:.*?)(?:does not match the constraint|conflicts with|could not be resolved|not installable|requires .* ->)`)}, Excludes: []*regexp.Regexp{re(`curl error|Could not resolve host|Connection reset|timed out|SSL certificate`)}},

		{ID: "bazel-remote-cache-network", Category: model.CategoryNetworkFailure, Provider: "Bazel remote cache", Operation: "cache-transport", ErrorFamily: "remote-cache-connection-reset", Weight: 58, SignalGroup: "connectivity", Summary: "Bazel lost the network connection to its remote cache", Recommendation: "Check the remote cache endpoint and network path, then retry with bounded backoff.", Patterns: []*regexp.Regexp{re(`Remote Cache(?s:.*?)(?:Connection reset|UNAVAILABLE: io exception|connection closed before message completed)`)}},
		{ID: "bazel-remote-cache-service", Category: model.CategoryCacheFailure, Provider: "Bazel remote cache", Operation: "cache-upload-download", ErrorFamily: "remote-cache-service-failure", Weight: 61, SignalGroup: "cache", Summary: "Bazel remote cache upload or download failed", Recommendation: "Retry without relying on the remote cache when possible and investigate cache capacity, channel stability, and timeouts.", Patterns: []*regexp.Regexp{re(`remote cache(?s:.*?)(?:ClosedChannelException|DEADLINE_EXCEEDED|deadline exceeded|upload.*timed out|Error uploading results)`)}, Excludes: []*regexp.Regexp{re(`Connection reset|UNAVAILABLE: io exception`)}},
		{ID: "bazel-repository-undefined", Category: model.CategoryCodeFailure, Provider: "Bazel", Operation: "repository-resolution", ErrorFamily: "repository-not-defined", Weight: -62, SignalGroup: "deterministic", Summary: "A Bazel external repository referenced by the build is not defined", Recommendation: "Declare or correct the repository name in MODULE.bazel, WORKSPACE, or the referencing label.", Patterns: []*regexp.Regexp{re(`Repository ['\"]?[^'\"]+['\"]? is not defined|no such package '@[^']+//'.*repository`)}},
		{ID: "bazel-checksum-lock", Category: model.CategoryCodeFailure, Provider: "Bazel", Operation: "module-resolution", ErrorFamily: "checksum-lock-policy", Weight: -64, SignalGroup: "deterministic", Summary: "Bazel module resolution rejected a missing checksum or stale lockfile", Recommendation: "Update the Bazel module lockfile or provide the required checksum under the configured lock policy.", Patterns: []*regexp.Regexp{re(`Cannot fetch a file without a checksum in ENFORCE mode|Missing checksum for registry file|--lockfile_mode=update`)}},
		{ID: "bazel-jdk-toolchain", Category: model.CategoryCodeFailure, Provider: "Bazel Java toolchain", Operation: "compile", ErrorFamily: "jdk-toolchain-incompatibility", Weight: -61, SignalGroup: "deterministic", Summary: "The Bazel Java toolchain is incompatible with the selected JDK", Recommendation: "Use a supported JDK/Bazel toolchain combination or update the bundled Java tooling.", Patterns: []*regexp.Regexp{re(`NoSuchFieldError: Class com\.sun\.tools\.javac|Error Prone.*incompatible with JDK|remote_java_tools.*incompatible`)}},
		{ID: "bazel-internal-error", Category: model.CategoryCodeFailure, Provider: "Bazel", Operation: "build-execution", ErrorFamily: "deterministic-internal-error", Weight: -55, SignalGroup: "deterministic", Summary: "Bazel crashed on a deterministic internal or configuration error", Recommendation: "Preserve the stack trace, reproduce with the same Bazel version, and review configuration or report the tool defect.", Patterns: []*regexp.Regexp{re(`FATAL: bazel crashed due to an internal error(?s:.*?)(?:IllegalStateException|NoSuchFieldError|RuntimeException)`)}, Excludes: []*regexp.Regexp{re(`OutOfMemoryError|unable to create native thread|Cannot fetch a file without a checksum`)}},
		{ID: "bazel-named-pipe-deadlock", Category: model.CategoryCodeFailure, Provider: "Bazel", Operation: "build-event-output", ErrorFamily: "named-pipe-deadlock", Weight: -53, SignalGroup: "deterministic", Summary: "Bazel build-event or execution-log outputs deadlocked on named pipes", Recommendation: "Do not point both build-event and execution-log outputs at blocking named pipes; change the output configuration.", Patterns: []*regexp.Regexp{re(`Waiting for build events upload.*BinaryFormatFileTransport|execution_log_compact_file.*build_event_binary_file.*named pipes|pipe backpressure.*build never completes`)}},

		{ID: "terraform-registry-timeout", Category: model.CategoryDependencyRegistry, Provider: "Terraform Registry", Operation: "provider-query", ErrorFamily: "registry-timeout", Weight: 66, SignalGroup: "connectivity", Summary: "Terraform provider registry access timed out", Recommendation: "Check registry.terraform.io or releases.hashicorp.com health and retry before changing provider constraints.", Patterns: []*regexp.Regexp{re(`(?:registry\.terraform\.io|releases\.hashicorp\.com)(?s:.*?)(?:Client\.Timeout exceeded|i/o timeout|ETIMEDOUT|request canceled while waiting for connection)`)}},
		{ID: "terraform-registry-network", Category: model.CategoryNetworkFailure, Provider: "Terraform", Operation: "registry-connectivity", ErrorFamily: "network-or-dns-failure", Weight: 68, SignalGroup: "connectivity", Summary: "Terraform could not reach its registry because of a local network, DNS, or socket failure", Recommendation: "Check DNS, VPN/proxy, firewall, and socket policy before changing Terraform configuration.", Patterns: []*regexp.Regexp{re(`(?:registry\.terraform\.io|terraform\.localhost)(?s:.*?)(?:lookup .* no such host|read: connection refused|socket is not connected|connectex:.*socket|access a socket.*forbidden|Could not resolve host)`)}},
		{ID: "terraform-registry-invalid-response", Category: model.CategoryDependencyRegistry, Provider: "Terraform Registry", Operation: "provider-query", ErrorFamily: "invalid-registry-response", Weight: 67, SignalGroup: "registry", Summary: "Terraform Registry returned provider metadata that Terraform could not accept", Recommendation: "Treat this as registry or published-metadata failure; retry after checking the provider/registry incident before editing constraints.", Patterns: []*regexp.Regexp{re(`registry response includes invalid version string|could not query provider registry(?s:.*?)(?:invalid response|invalid version)`)}},
		{ID: "terraform-provider-version-conflict", Category: model.CategoryCodeFailure, Provider: "Terraform", Operation: "provider-resolution", ErrorFamily: "provider-version-conflict", Weight: -68, SignalGroup: "deterministic", Summary: "Terraform provider constraints or the dependency lock file are incompatible", Recommendation: "Correct the provider constraints or run the appropriate controlled lockfile upgrade after reviewing the intended version change.", Patterns: []*regexp.Regexp{re(`locked provider .* does not match configured version constraint|no available releases match the given constraints|must use terraform init -upgrade to allow selection of new versions`)}},
		{ID: "terraform-provider-not-found", Category: model.CategoryCodeFailure, Provider: "Terraform", Operation: "provider-resolution", ErrorFamily: "provider-source-not-found", Weight: -67, SignalGroup: "deterministic", Summary: "Terraform could not find the configured provider source", Recommendation: "Correct the provider source address, resource/provider typo, module required_providers declaration, or mirror contents.", Patterns: []*regexp.Regexp{re(`provider registry registry\.terraform\.io does not have a provider named|provider .* was not found in any of the search locations|Did you intend to use .*? must specify that source address`)}},
		{ID: "terraform-mirror-config", Category: model.CategoryCodeFailure, Provider: "Terraform", Operation: "provider-mirror", ErrorFamily: "mirror-configuration", Weight: -64, SignalGroup: "deterministic", Summary: "Terraform provider mirror configuration or layout is incompatible", Recommendation: "Review provider_installation, mirror URL/layout, provider source addresses, and the mirror protocol used by the repository.", Patterns: []*regexp.Regexp{re(`provider mirror at .* was not found|failed to query provider mirror|cannot search .*\.terraform\.d/providers|filesystem_mirror`)}},
		{ID: "terraform-provider-cache-conflict", Category: model.CategoryCodeFailure, Provider: "Terraform", Operation: "provider-cache", ErrorFamily: "cache-layout-conflict", Weight: -61, SignalGroup: "deterministic", Summary: "Terraform provider cache layout or local filesystem state is conflicting", Recommendation: "Clean or repair the affected provider cache directory and verify plugin_cache_dir/mirror paths before rerunning init.", Patterns: []*regexp.Regexp{re(`Failed to install provider from shared cache|Error while importing .* from the shared cache directory|failed to create directory(?s:.*?)Cannot create a file when that file already exists`)}},
		{ID: "terraform-state-lock-contention", Category: model.CategoryConcurrencyConflict, Provider: "Terraform State", Operation: "state-lock", ErrorFamily: "state-lock-contention", Weight: 59, SignalGroup: "state-lock", Summary: "Terraform state is locked by another or stale operation", Recommendation: "Identify the active holder, wait or resolve the stale lock safely, and avoid disabling locking unless ownership is certain.", Patterns: []*regexp.Regexp{re(`(?:Error acquiring the state lock|Error locking state)(?s:.*?)(?:state blob is already locked|ConditionalCheckFailedException|workspace already locked|already locked for workspace|Precondition Failed|conditionNotMet)`)}, Excludes: []*regexp.Regexp{re(`NotImplemented|Unexpected HTTP response code|Incorrect function|cannot find the file specified`)}},
		{ID: "terraform-backend-incompatibility", Category: model.CategoryCodeFailure, Provider: "Terraform Backend", Operation: "state-backend", ErrorFamily: "backend-incompatibility", Weight: -69, SignalGroup: "deterministic", Summary: "Terraform state backend behavior or configuration is incompatible", Recommendation: "Review backend support, permissions, HTTP/S3 semantics, platform paths, and backend configuration before retrying.", Patterns: []*regexp.Regexp{re(`Error acquiring the state lock(?s:.*?)(?:api error NotImplemented|Unexpected HTTP response code|Incorrect function\.|A header you provided implies functionality that is not implemented)|failed to delete the lock file(?s:.*?)AccessDenied`)}},
		{ID: "terraform-local-path", Category: model.CategoryCodeFailure, Provider: "Terraform", Operation: "local-filesystem", ErrorFamily: "invalid-local-path", Weight: -58, SignalGroup: "deterministic", Summary: "Terraform could not use a configured local provider/cache path", Recommendation: "Use an expanded absolute path supported by the current operating system and verify that it exists.", Patterns: []*regexp.Regexp{re(`cannot search \$HOME/.*no such file or directory|lstat \$HOME/.*no such file or directory|UNC paths are not supported`)}},

		{ID: "rubygems-network", Category: model.CategoryNetworkFailure, Provider: "RubyGems", Operation: "package-index", ErrorFamily: "registry-connectivity", Weight: 58, SignalGroup: "connectivity", Summary: "Bundler could not reach RubyGems because of a network or TLS transport failure", Recommendation: "Check DNS, routing, proxy/TLS interception, and RubyGems availability before changing the Gemfile.", Patterns: []*regexp.Regexp{re(`(?:rubygems\.org|index\.rubygems\.org)(?s:.*?)(?:EHOSTUNREACH|No route to host|unexpected eof while reading|Failed to open TCP connection|Connection reset|execution expired|Net::OpenTimeout|Net::ReadTimeout)`)}},
		{ID: "rubygems-service-error", Category: model.CategoryDependencyRegistry, Provider: "RubyGems", Operation: "package-index", ErrorFamily: "registry-server-error", Weight: 60, SignalGroup: "connectivity", Summary: "RubyGems returned a server-side failure", Recommendation: "Check RubyGems status and retry after recovery; do not rewrite dependency constraints because of a 5xx response.", Patterns: []*regexp.Regexp{re(`(?:rubygems\.org|Bundler::HTTPError|Net::HTTPFatalError)(?s:.*?)(?:500|502|503|504)\s*(?:Service Unavailable|Bad Gateway|Gateway Timeout|Internal Server Error)?`)}},
		{ID: "bundler-dependency-conflict", Category: model.CategoryCodeFailure, Provider: "Bundler", Operation: "dependency-resolution", ErrorFamily: "dependency-conflict", Weight: -62, SignalGroup: "deterministic", Summary: "Bundler could not satisfy the Gemfile or lockfile dependency constraints", Recommendation: "Review the conflicting gem/Ruby requirements and update the lockfile deliberately.", Patterns: []*regexp.Regexp{re(`Bundler could not find compatible versions|Your Ruby version is .* but your Gemfile specified|Your bundle is locked to .* but that version could not be found|already activated .* but your Gemfile requires`)}},
		{ID: "bundler-gem-not-found", Category: model.CategoryCodeFailure, Provider: "Bundler", Operation: "dependency-resolution", ErrorFamily: "gem-not-found", Weight: -60, SignalGroup: "deterministic", Summary: "Bundler could not find a required gem in the configured or local sources", Recommendation: "Verify the gem name/version, source declarations, credentials, and lockfile rather than retrying blindly.", Patterns: []*regexp.Regexp{re(`Bundler::GemNotFound|Could not find (?:gem ['\"]|[A-Za-z0-9_.-]+-[0-9][^\s]*) .*?(?:in locally installed gems|in any of the sources)`)}},
		{ID: "bundler-platform-lock", Category: model.CategoryCodeFailure, Provider: "Bundler", Operation: "platform-resolution", ErrorFamily: "unsupported-lock-platform", Weight: -60, SignalGroup: "deterministic", Summary: "The Bundler lockfile does not support the current runner platform", Recommendation: "Add the intended platform to the lockfile and commit the controlled lockfile change.", Patterns: []*regexp.Regexp{re(`Your bundle only supports platforms .* but your local platform is|bundle lock --add-platform`)}},
		{ID: "bundler-missing-gemfile", Category: model.CategoryCodeFailure, Provider: "Bundler", Operation: "project-discovery", ErrorFamily: "gemfile-not-found", Weight: -58, SignalGroup: "deterministic", Summary: "Bundler could not locate the project's Gemfile", Recommendation: "Run Bundler from the correct working directory or provide the intended BUNDLE_GEMFILE path.", Patterns: []*regexp.Regexp{re(`Could not locate Gemfile or \.bundle/ directory`)}},
		{ID: "bundler-permission", Category: model.CategoryCodeFailure, Provider: "Bundler", Operation: "filesystem-write", ErrorFamily: "permission-denied", Weight: -58, SignalGroup: "deterministic", Summary: "Bundler cannot write to a required cache or lockfile path", Recommendation: "Correct ownership/permissions or use a writable bundle/cache path; do not run the CI job as an unnecessarily privileged user.", Patterns: []*regexp.Regexp{re(`Bundler::PermissionError|There was an error while trying to write to .*Gemfile\.lock|grant write permissions for that path`)}, Excludes: []*regexp.Regexp{re(`ENOSPC|No space left on device`)}},
		{ID: "rubygems-native-extension", Category: model.CategoryCodeFailure, Provider: "RubyGems", Operation: "native-extension-build", ErrorFamily: "native-extension-build-failure", Weight: -56, SignalGroup: "deterministic", Summary: "A gem native extension failed to compile", Recommendation: "Inspect the first compiler/make error and install the required compiler, headers, and system libraries.", Patterns: []*regexp.Regexp{re(`Gem::Ext::BuildError|Failed to build gem native extension|An error occurred while installing .* and Bundler cannot continue`)}},
		{ID: "bundler-checksum", Category: model.CategoryCacheFailure, Provider: "Bundler", Operation: "artifact-integrity", ErrorFamily: "gem-checksum-mismatch", Weight: 56, SignalGroup: "cache", Summary: "A downloaded gem checksum does not match the registry metadata", Recommendation: "Discard the affected cache entry and retry; investigate a proxy/CDN or upstream metadata issue if the mismatch repeats.", Patterns: []*regexp.Regexp{re(`Bundler::SecurityError(?s:.*?)(?:checksum .* does not match|downloaded gem may be corrupt)`)}},
		{ID: "bundler-internal-error", Category: model.CategoryToolchainFailure, Provider: "Bundler", Operation: "dependency-resolution", ErrorFamily: "internal-tool-error", Weight: 45, SignalGroup: "toolchain", Summary: "Bundler raised an internal deterministic exception while resolving the project", Recommendation: "Capture the stack trace, reproduce with the same lockfile, and update or report the Bundler version if necessary.", Patterns: []*regexp.Regexp{re(`Bundler::FriendlyErrors:.*(?:NoMethodError|undefined method)|bundler/resolver\.rb(?s:.*?)undefined method`)}},

		{ID: "aws-invalid-security-token", Category: model.CategoryCodeFailure, Provider: "AWS", Operation: "authentication", ErrorFamily: "invalid-security-token", Weight: -70, SignalGroup: "deterministic", Summary: "AWS rejected the configured security token", Recommendation: "Rotate or correct the AWS access key/session token and verify that credentials from an earlier step were cleared.", Patterns: []*regexp.Regexp{re(`InvalidClientTokenId|security token included in the request is invalid`)}},
		{ID: "aws-assume-role-denied", Category: model.CategoryCodeFailure, Provider: "AWS IAM", Operation: "assume-role", ErrorFamily: "iam-access-denied", Weight: -70, SignalGroup: "deterministic", Summary: "AWS IAM denied the requested role assumption", Recommendation: "Correct the role trust policy, caller permissions, role ARN, and OIDC subject/audience conditions.", Patterns: []*regexp.Regexp{re(`not authorized to perform:\s*sts:AssumeRole|AccessDenied(?s:.*?)(?:AssumeRole|sts:)`)}},
		{ID: "aws-oidc-configuration", Category: model.CategoryCodeFailure, Provider: "AWS OIDC", Operation: "authentication", ErrorFamily: "oidc-configuration", Weight: -66, SignalGroup: "deterministic", Summary: "AWS OIDC authentication is missing or misconfigured", Recommendation: "Verify id-token: write permission, the OIDC provider URL/thumbprint, audience, and IAM trust conditions.", Patterns: []*regexp.Regexp{re(`No OpenIDConnect provider found in your account|OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint|ACTIONS_ID_TOKEN_REQUEST_TOKEN.*not set|Credentials could not be loaded(?s:.*?)(?:permissions:\s*(?:\r?\n)?\s*contents:\s*read|id-token permission|pull request from a fork|dependabot)`)}},
		{ID: "gcp-invalid-grant", Category: model.CategoryCodeFailure, Provider: "Google Cloud", Operation: "authentication", ErrorFamily: "invalid-oauth-grant", Weight: -68, SignalGroup: "deterministic", Summary: "Google Cloud rejected the workload identity or service-account grant", Recommendation: "Verify the JWT signature, audience, service account, clock, workload identity provider, and token configuration.", Patterns: []*regexp.Regexp{re(`invalid_grant(?s:.*?)(?:Invalid JWT Signature|Invalid grant|audience|signature)|Invalid JWT Signature`)}},
		{ID: "vcpkg-hash-mismatch", Category: model.CategoryCodeFailure, Provider: "vcpkg", Operation: "artifact-integrity", ErrorFamily: "unexpected-artifact-hash", Weight: -67, SignalGroup: "deterministic", Summary: "vcpkg downloaded an artifact whose hash does not match the port definition", Recommendation: "Do not bypass the integrity check blindly; update the port/baseline or verify whether the upstream artifact was replaced.", Patterns: []*regexp.Regexp{re(`(?:vcpkg|downloads\\|downloads/|portfile)(?s:.*?)(?:unexpected hash|does not have the expected hash|Expected hash:)(?s:.*?)(?:Actual(?: hash)?\s*:)`)}},
		{ID: "vcpkg-source-not-found", Category: model.CategoryCodeFailure, Provider: "vcpkg", Operation: "source-download", ErrorFamily: "source-not-found", Weight: -64, SignalGroup: "deterministic", Summary: "A vcpkg port references a source archive that does not exist", Recommendation: "Correct the port version/source URL or update the vcpkg baseline; repeated retries will not fix a 404.", Patterns: []*regexp.Regexp{re(`vcpkg(?s:.*?)(?:status code 404|404\s*\(Not Found\))|vcpkg_download_distfile(?s:.*?)(?:status code 404|404\s*\(Not Found\))`)}},
		{ID: "vcpkg-upstream-challenge", Category: model.CategoryDependencyRegistry, Provider: "vcpkg upstream", Operation: "source-download", ErrorFamily: "upstream-download-interception", Weight: 55, SignalGroup: "connectivity", Summary: "An upstream host returned a protection or challenge page instead of the requested archive", Recommendation: "Check the upstream hosting incident/protection policy or use an approved mirror; do not update hashes to the challenge page.", Patterns: []*regexp.Regexp{re(`(?:vcpkg|archive|tar\.gz)(?s:.*?)(?:Anubis bot protection|bot protection challenge|challenge page instead of the requested archive)`)}},
		{ID: "cmake-compiler-not-found", Category: model.CategoryCodeFailure, Provider: "CMake", Operation: "toolchain-detection", ErrorFamily: "compiler-not-found", Weight: -66, SignalGroup: "deterministic", Summary: "CMake could not locate or validate the requested compiler", Recommendation: "Install/select the compiler and SDK, fix the generator/toolchain file, and verify PATH before rebuilding.", Patterns: []*regexp.Regexp{re(`No CMAKE_(?:C|CXX|CUDA|Fortran)_COMPILER could be found|The (?:C|CXX|CUDA|Fortran) compiler identification is unknown`)}},
		{ID: "cmake-package-not-found", Category: model.CategoryCodeFailure, Provider: "CMake", Operation: "dependency-discovery", ErrorFamily: "package-config-not-found", Weight: -58, SignalGroup: "deterministic", Summary: "CMake could not find a required package configuration", Recommendation: "Install the dependency or set CMAKE_PREFIX_PATH/<Package>_DIR to a compatible package configuration.", Patterns: []*regexp.Regexp{re(`Could not find a package configuration file provided by|Could NOT find [A-Za-z0-9_.+-]+ \(missing:`)}},
		{ID: "vcpkg-dependency-baseline", Category: model.CategoryCodeFailure, Provider: "vcpkg", Operation: "dependency-resolution", ErrorFamily: "dependency-not-in-baseline", Weight: -61, SignalGroup: "deterministic", Summary: "vcpkg could not resolve a dependency from the selected baseline", Recommendation: "Correct the port name or update/override the baseline deliberately.", Patterns: []*regexp.Regexp{re(`Cannot resolve a minimum constraint for dependency|dependency was not found in the baseline|Failed to find dependency abi`)}},
		{ID: "native-build-script-error", Category: model.CategoryCodeFailure, Provider: "native build", Operation: "build-script", ErrorFamily: "deterministic-build-script-error", Weight: -46, SignalGroup: "deterministic", Summary: "A native build wrapper failed on a deterministic local filesystem/tool invocation error", Recommendation: "Inspect the first failing compiler/resource-tool command and repair the local tool path or build script.", Patterns: []*regexp.Regexp{re(`windres-rc:.*(?:File exists|No such file or directory)|lld-link\s*:\s*error\s*:\s*could not open|make(?:\[\d+\])?: \*\*\*.*Error [12]`)}},

		{ID: "apt-network", Category: model.CategoryDependencyRegistry, Provider: "APT", Operation: "package-index", ErrorFamily: "repository-connectivity", Weight: 56, SignalGroup: "connectivity", Summary: "APT repository could not be reached reliably", Recommendation: "Check mirror/network health and retry before changing package configuration.", Patterns: []*regexp.Regexp{re(`Temporary failure resolving.*(ubuntu|debian)|Failed to fetch.*(502|503|504|Connection failed)|Some index files failed to download`)}},
		{ID: "apt-package-missing", Category: model.CategoryCodeFailure, Provider: "APT", Operation: "package-resolution", ErrorFamily: "package-not-found", Weight: -28, SignalGroup: "deterministic", Summary: "APT package could not be located", Recommendation: "Verify repository setup, operating-system release, and package name.", Patterns: []*regexp.Regexp{re(`E: Unable to locate package|Package .* has no installation candidate`)}},

		{ID: "github-artifact-intermediary", Category: model.CategoryNetworkFailure, Provider: "GitHub Artifacts", Operation: "artifact-transfer", ErrorFamily: "intermediary-failure", Weight: 46, SignalGroup: "connectivity", Summary: "A GitHub Artifacts intermediary rejected the request", Recommendation: "Retry with bounded backoff and check GitHub Actions connectivity before changing workflow code.", Patterns: []*regexp.Regexp{re(`(CreateArtifact|FinalizeArtifact|artifact).*(Error from intermediary|intermediary with HTTP status code)`)}},
		{ID: "github-artifact-malformed-response", Category: model.CategoryNetworkFailure, Provider: "GitHub Artifacts", Operation: "artifact-transfer", ErrorFamily: "malformed-service-response", Weight: 46, SignalGroup: "connectivity", Summary: "GitHub Artifacts returned an unexpected non-JSON response", Recommendation: "Treat this as an upstream/service response failure and retry after checking GitHub Actions health.", Patterns: []*regexp.Regexp{re(`Failed to (Create|Finalize)Artifact: Unexpected token.*DOCTYPE|Failed to (Create|Finalize)Artifact:.*not valid JSON`)}},
		{ID: "github-artifact-5xx", Category: model.CategoryNetworkFailure, Provider: "GitHub Artifacts", Operation: "artifact-transfer", ErrorFamily: "service-server-error", Weight: 52, SignalGroup: "connectivity", Summary: "GitHub Artifacts returned a server-side error", Recommendation: "Retry with bounded backoff and check GitHub Actions service health.", Patterns: []*regexp.Regexp{re(`(artifact|Artifact|ContainersItems|pipelines\.actions\.githubusercontent\.com).*(500|502|503|504|Service Unavailable)|Status Code:\s*(500|502|503|504)(?s:.*?)(ContainersItems|pipelines\.actions\.githubusercontent\.com)|Unable to get ContainersItems|A (500|502|503|504) status code has been received|Received http (500|502|503|504) during chunk upload`)}},
		{ID: "github-artifact-bad-request", Category: model.CategoryCodeFailure, Provider: "GitHub Artifacts", Operation: "artifact-upload", ErrorFamily: "bad-request", Weight: -32, SignalGroup: "deterministic", Summary: "GitHub Artifacts rejected the upload request as invalid", Recommendation: "Review artifact paths, names, action version, and request size before retrying.", Patterns: []*regexp.Regexp{re(`Unable to upload chunk(?s:.*?)Status Code:\s*400|Artifact(?s:.*?)Status Code:\s*400(?s:.*?)Bad Request`)}},
		{ID: "github-runner-lost", Category: model.CategoryRunnerFailure, Provider: "GitHub Actions", Operation: "runner-communication", ErrorFamily: "runner-lost", Weight: 62, SignalGroup: "runner", Summary: "GitHub Actions lost communication with the runner", Recommendation: "Treat this as runner/infrastructure failure; retry on a fresh runner.", Patterns: []*regexp.Regexp{re(`Lost communication with the server|The runner has received a shutdown signal|runner.*(disconnected|lost communication)|The self-hosted runner.*lost`)}},
		{ID: "github-runner-not-found", Category: model.CategoryRunnerFailure, Provider: "GitHub Actions", Operation: "runner-allocation", ErrorFamily: "runner-not-found", Weight: 58, SignalGroup: "runner", Summary: "A suitable runner could not be allocated", Recommendation: "Check runner labels/capacity and GitHub Actions service health.", Patterns: []*regexp.Regexp{re(`Runner not found|No runner matching the specified labels|Waiting for a runner to pick up this job`)}},
		{ID: "github-cancelled", Category: model.CategoryUnknown, Provider: "GitHub Actions", Operation: "job-execution", ErrorFamily: "task-cancelled", Weight: 18, SignalGroup: "runner", Summary: "The task was cancelled without a specific root cause", Recommendation: "Inspect timeout, concurrency cancellation, runner shutdown, and upstream workflow conditions.", Patterns: []*regexp.Regexp{re(`The operation was canceled|A task was cancelled|The job was canceled|The operation was cancelled`)}},

		{ID: "helm-operation-lock", Category: model.CategoryConcurrencyConflict, Provider: "Helm", Operation: "release-operation", ErrorFamily: "release-operation-in-progress", Weight: 66, SignalGroup: "release-lock", Summary: "A Helm release is locked by another or stale operation", Recommendation: "Confirm whether an install/upgrade/rollback is active; resolve stale pending state safely before retrying.", Patterns: []*regexp.Regexp{re(`another operation \(install/upgrade/rollback\) is in progress|release .* is in a pending-(?:install|upgrade|rollback) state`)}},
		{ID: "helm-template-render", Category: model.CategoryCodeFailure, Provider: "Helm", Operation: "template-render", ErrorFamily: "template-error", Weight: -66, SignalGroup: "deterministic", Summary: "Helm chart template rendering failed deterministically", Recommendation: "Fix the cited template, values type, include/tpl scope, or missing field before retrying.", Patterns: []*regexp.Regexp{re(`(?:INSTALLATION|UPGRADE|template) FAILED(?s:.*?)(?:template:|error calling (?:tpl|include)|wrong type for value)|executing .* at <.*>:\s*(?:error calling (?:tpl|include)|wrong type for value)|cannot retrieve Template\.Basepath|wrong type for value; expected`)}},
		{ID: "helm-invalid-version", Category: model.CategoryCodeFailure, Provider: "Helm", Operation: "version-validation", ErrorFamily: "invalid-semantic-version", Weight: -62, SignalGroup: "deterministic", Summary: "Helm rejected an invalid Kubernetes or chart semantic version", Recommendation: "Pass a valid semantic version supported by Helm or normalize the provider-specific version string.", Patterns: []*regexp.Regexp{re(`invalid kube version .*Invalid Semantic Version|Invalid Semantic Version(?s:.*?)helm`)}},
		{ID: "helm-resource-not-found", Category: model.CategoryCodeFailure, Provider: "Helm", Operation: "release-upgrade", ErrorFamily: "resource-not-found", Weight: -58, SignalGroup: "deterministic", Summary: "Helm could not find a resource required by the release operation", Recommendation: "Inspect the rendered manifests and release state; correct resource names/ownership before retrying.", Patterns: []*regexp.Regexp{re(`(?:UPGRADE|INSTALLATION) FAILED: No resource with the name .* found|Looks like there are no changes for`)}},
		{ID: "k8s-sysctl-forbidden", Category: model.CategoryCodeFailure, Provider: "Kubernetes", Operation: "pod-admission", ErrorFamily: "forbidden-sysctl", Weight: -66, SignalGroup: "deterministic", Summary: "Kubernetes rejected an unsafe or disallowed sysctl", Recommendation: "Remove the sysctl or explicitly allow it on the target nodes according to cluster policy.", Patterns: []*regexp.Regexp{re(`SysctlForbidden|unsafe sysctl .* is not allowed`)}},
		{ID: "k8s-network-config", Category: model.CategoryCodeFailure, Provider: "Kubernetes", Operation: "pod-network", ErrorFamily: "pod-network-not-configured", Weight: -64, SignalGroup: "deterministic", Summary: "Kubernetes pod networking is not configured for the node", Recommendation: "Fix CNI/Kubenet configuration and ensure the node has a PodCIDR before retrying workloads.", Patterns: []*regexp.Regexp{re(`network is not ready(?s:.*?)(?:lack of PodCIDR|does not have netConfig)|Kubenet does not have netConfig|NetworkPlugin.*failed.*(?:PodCIDR|CNI)`)}},
		{ID: "k8s-node-disk-pressure", Category: model.CategoryResourceExhaustion, Provider: "Kubernetes node", Operation: "image-storage", ErrorFamily: "node-disk-pressure", Weight: 68, SignalGroup: "resource", Summary: "A Kubernetes node is under disk pressure and image garbage collection cannot free enough space", Recommendation: "Free node/image filesystem space, adjust eviction thresholds, or move the job to a node with sufficient storage.", Patterns: []*regexp.Regexp{re(`node was low on resource: nodefs|ImageGCFailed|failed to garbage collect required amount of images|DiskPressure`)}},
		{ID: "k8s-pleg-unhealthy", Category: model.CategoryRunnerFailure, Provider: "Kubernetes node", Operation: "kubelet-runtime", ErrorFamily: "pleg-unhealthy", Weight: 67, SignalGroup: "runner", Summary: "The Kubernetes node runtime health loop is unresponsive", Recommendation: "Treat this as node/container-runtime infrastructure failure; inspect kubelet and CRI health or reschedule on a healthy node.", Patterns: []*regexp.Regexp{re(`PLEG is not healthy|pleg was last seen active`)}},
		{ID: "k8s-test-expected-error", Category: model.CategoryCodeFailure, Provider: "Kubernetes test", Operation: "test", ErrorFamily: "expected-error-missing", Weight: -60, SignalGroup: "deterministic", Summary: "A Kubernetes test expected a deterministic error but the operation succeeded", Recommendation: "Inspect the changed validation/admission behavior and test expectation.", Patterns: []*regexp.Regexp{re(`Expected an error to have occurred\.?(?s:.*?)<nil>:\s*nil|should be forbidden(?s:.*?)Got:\s*<nil>`)}},
		{ID: "k8s-test-readiness-timeout", Category: model.CategoryTestFlake, Provider: "Kubernetes test", Operation: "test", ErrorFamily: "pod-readiness-timeout", Weight: 44, SignalGroup: "flake", Summary: "A Kubernetes end-to-end test timed out waiting for a pod or resource condition", Recommendation: "Rerun the isolated test and inspect scheduler, node readiness, image pulls, and resource timing before attributing it to code.", Patterns: []*regexp.Regexp{re(`\[FAILED\] Timed out after [0-9.]+s(?s:.*?)(?:expected pod to be running and ready|timed out waiting for the condition)|timed out waiting for the condition(?s:.*?)(?:In \[It\]|Kubernetes e2e)`)}},
		{ID: "broken-pipe-network", Category: model.CategoryNetworkFailure, Provider: "network", Operation: "stream-transfer", ErrorFamily: "broken-pipe", Weight: 48, SignalGroup: "connectivity", Summary: "A network stream closed with a broken pipe", Recommendation: "Check the remote service and connection lifecycle; retry with bounded backoff if the operation is safe.", Patterns: []*regexp.Regexp{re(`write: broken pipe|BrokenPipeError|EPIPE`)}},
		{ID: "github-cache-miss", Category: model.CategoryCodeFailure, Provider: "GitHub Actions Cache", Operation: "cache-key", ErrorFamily: "cache-miss", Weight: -42, SignalGroup: "cache", Summary: "The requested cache key was not available", Recommendation: "Review the cache key, scope, branch, and fail-on-cache-miss policy.", Patterns: []*regexp.Regexp{re(`Cache not found for input keys|Failed to restore cache entry.*fail-on-cache-miss|cache miss.*fail-on-cache-miss`)}},
		{ID: "github-cache", Category: model.CategoryCacheFailure, Provider: "GitHub Actions Cache", Operation: "cache-service", ErrorFamily: "cache-service-failure", Weight: 48, SignalGroup: "cache", Summary: "GitHub Actions cache service failed", Recommendation: "Continue without cache when possible and retry after cache service recovery.", Patterns: []*regexp.Regexp{re(`Cache service responded with.*(500|502|503|504)|Unable to reserve cache|Failed to save cache|Failed to restore cache`)}, Excludes: []*regexp.Regexp{re(`fail-on-cache-miss|Cache not found for input keys`)}},

		{ID: "connection-reset", Category: model.CategoryNetworkFailure, Provider: "network", Operation: "remote-request", ErrorFamily: "connection-reset", Weight: 38, SignalGroup: "connectivity", Summary: "A network connection was reset by the remote side", Recommendation: "Check the named service and retry with bounded backoff before changing code.", Patterns: []*regexp.Regexp{re(`ECONNRESET|connection reset by peer|socket hang up|socket disconnected before secure TLS connection|Client network socket disconnected`)}},
		{ID: "connection-refused", Category: model.CategoryNetworkFailure, Provider: "network", Operation: "remote-request", ErrorFamily: "connection-refused", Weight: 42, SignalGroup: "connectivity", Summary: "A remote service refused the network connection", Recommendation: "Check the target service and network path, then retry with bounded backoff.", Patterns: []*regexp.Regexp{re(`ECONNREFUSED|connection refused`)}},
		{ID: "proxy-failure", Category: model.CategoryNetworkFailure, Provider: "proxy", Operation: "connect", ErrorFamily: "proxy-connectivity", Weight: 46, SignalGroup: "connectivity", Summary: "The configured network proxy could not be reached", Recommendation: "Verify proxy address, credentials, and network reachability.", Patterns: []*regexp.Regexp{re(`ProxyError|Cannot connect to proxy|proxyconnect tcp|connect .*proxy.*(timed out|refused)`)}},
		{ID: "timeout-network", Category: model.CategoryNetworkFailure, Provider: "network", Operation: "remote-request", ErrorFamily: "timeout", Weight: 40, SignalGroup: "connectivity", Summary: "A remote network operation timed out", Recommendation: "Check the named external provider and retry with bounded backoff.", Patterns: []*regexp.Regexp{re(`i/o timeout|TLS handshake timeout|context deadline exceeded.*(http|download|connect)|connection timed out|ETIMEDOUT|timed out after \d+ seconds`)}},
		{ID: "dns-failure", Category: model.CategoryNetworkFailure, Provider: "DNS", Operation: "name-resolution", ErrorFamily: "dns-failure", Weight: 50, SignalGroup: "connectivity", Summary: "DNS name resolution failed", Recommendation: "Verify DNS and provider availability before changing project code.", Patterns: []*regexp.Regexp{re(`Temporary failure in name resolution|Temporary failure resolving|no such host|Name or service not known|nodename nor servname provided|Could not resolve host|Failed to resolve|getaddrinfo ENOTFOUND|\bENOTFOUND\s+[A-Za-z0-9.-]+`)}},
		{ID: "tls-failure", Category: model.CategoryNetworkFailure, Provider: "network", Operation: "tls", ErrorFamily: "tls-failure", Weight: 44, SignalGroup: "connectivity", Summary: "TLS negotiation or certificate validation failed", Recommendation: "Check certificate validity, system clock, proxy interception, and provider health.", Patterns: []*regexp.Regexp{re(`x509: certificate|certificate verify failed|CERTIFICATE_VERIFY_FAILED|SSLCertVerificationError|SSL certificate problem|unable to verify the first certificate|UNABLE_TO_VERIFY_LEAF_SIGNATURE|PKIX path building failed|unable to find valid certification path|remote error: tls|TLS handshake`)}, Excludes: []*regexp.Regexp{re(`expected result:|expected success, built chain|tls: insufficient security level|127\.0\.0\.1.*--- FAIL`)}},

		{ID: "disk-full", Category: model.CategoryResourceExhaustion, Provider: "runner", Operation: "filesystem", ErrorFamily: "disk-full", Weight: 55, SignalGroup: "resource", Summary: "Runner disk space was exhausted", Recommendation: "Clean build artifacts/caches or use a runner with more disk capacity.", Patterns: []*regexp.Regexp{re(`no space left on device|ENOSPC|disk quota exceeded`)}},
		{ID: "oom", Category: model.CategoryResourceExhaustion, Provider: "runner", Operation: "memory", ErrorFamily: "out-of-memory", Weight: 54, SignalGroup: "resource", Summary: "The job exceeded available memory", Recommendation: "Reduce concurrency/memory usage or use a larger runner.", Patterns: []*regexp.Regexp{re(`Out of memory|Cannot allocate memory|ENOMEM|Killed process .* out of memory|fatal error: runtime: out of memory|Java heap space|exit code 137`)}},

		{ID: "ruby-registry-network", Category: model.CategoryNetworkFailure, Provider: "RubyGems", Operation: "package-index", ErrorFamily: "registry-connectivity", Weight: 54, SignalGroup: "connectivity", Summary: "RubyGems or Bundler could not reach the package index", Recommendation: "Check DNS, routing, TLS, proxy, and RubyGems service health before changing the Gemfile or lockfile.", Patterns: []*regexp.Regexp{re(`Could not fetch specs from https?://(?:index\.)?rubygems\.org.*(?:Failed to open TCP connection|No route to host|unexpected eof|connection reset|execution expired|timed out)|Unable to download data from https?://(?:api\.)?rubygems\.org/.*SSL_connect|Network error while fetching https?://bundler\.rubygems\.org`)}},
		{ID: "ruby-registry-server", Category: model.CategoryDependencyRegistry, Provider: "RubyGems", Operation: "package-index", ErrorFamily: "registry-server-error", Weight: 56, SignalGroup: "connectivity", Summary: "RubyGems returned a server-side or rate-limit error", Recommendation: "Retry with bounded backoff and check RubyGems status before changing dependency versions.", Patterns: []*regexp.Regexp{re(`(?:rubygems\.org|index\.rubygems\.org).*(?:429 Too Many Requests|5\d\d (?:Service Unavailable|Internal Server Error|Bad Gateway|Gateway Timeout))|Bundler::HTTPError:(?s:.*)(?:Net::HTTPTooManyRequests|503 Service Unavailable|502 Bad Gateway|504 Gateway Timeout)|Net::HTTPFatalError:\s*5\d\d`)}},
		{ID: "ruby-dependency-resolution", Category: model.CategoryCodeFailure, Provider: "Bundler", Operation: "dependency-resolution", ErrorFamily: "gem-resolution-failure", Weight: -56, SignalGroup: "deterministic", Summary: "Bundler could not satisfy the Gemfile, lockfile, Ruby version, or platform requirements", Recommendation: "Review Gemfile constraints, the lockfile, selected Ruby version, gem sources, and target platforms.", Patterns: []*regexp.Regexp{re(`Bundler could not find compatible versions for gem|Your Ruby version is .* but your Gemfile specified|requires ruby version .* incompatible with the current version|Your bundle is locked to .* but that version could not be found|Could not find gem .* in (?:any of the sources|locally installed gems)|Could not find .* in any of the sources \(Bundler::GemNotFound\)|Bundler::GemNotFound|Your bundle only supports platforms .* but your local platform is|current platform .* is not in the lockfile|Could not locate Gemfile or \.bundle/ directory`)}},
		{ID: "ruby-permission", Category: model.CategoryCodeFailure, Provider: "Ruby/Bundler", Operation: "filesystem", ErrorFamily: "permission-denied", Weight: -50, SignalGroup: "deterministic", Summary: "RubyGems or Bundler lacks permission to write required files", Recommendation: "Correct ownership and write permissions or install into an application-local bundle path; do not run the build as root blindly.", Patterns: []*regexp.Regexp{re(`Bundler::PermissionError|Gem::FilePermissionError|There was an error while trying to write to .*Gemfile\.lock|You don't have write permissions for`)}, Excludes: []*regexp.Regexp{re(`No space left on device|ENOSPC|disk quota exceeded`)}},
		{ID: "ruby-native-extension", Category: model.CategoryCodeFailure, Provider: "RubyGems", Operation: "native-extension-build", ErrorFamily: "native-extension-build-error", Weight: -52, SignalGroup: "deterministic", Summary: "A Ruby gem native extension failed to compile", Recommendation: "Inspect the first compiler/configure error and install the required headers, compiler, library, or compatible gem version.", Patterns: []*regexp.Regexp{re(`Gem::Ext::BuildError:.*Failed to build gem native extension|ERROR: Failed to build gem native extension|An error occurred while installing .* and Bundler cannot continue`)}},
		{ID: "ruby-activation-conflict", Category: model.CategoryCodeFailure, Provider: "RubyGems", Operation: "gem-activation", ErrorFamily: "activated-version-conflict", Weight: -54, SignalGroup: "deterministic", Summary: "An already activated Ruby gem conflicts with the Gemfile requirement", Recommendation: "Align the default/activated gem version with the lockfile or update Bundler and the Ruby image consistently.", Patterns: []*regexp.Regexp{re(`You have already activated .* but your Gemfile requires|check_for_activated_spec!.*Gem::LoadError`)}},
		{ID: "ruby-checksum", Category: model.CategoryCacheFailure, Provider: "RubyGems", Operation: "package-verification", ErrorFamily: "checksum-mismatch", Weight: 58, SignalGroup: "cache", Summary: "A downloaded Ruby gem failed checksum verification", Recommendation: "Discard the cached archive, retry from the trusted source, and investigate mirrors or proxies if the mismatch repeats.", Patterns: []*regexp.Regexp{re(`checksum for .*\.gem does not match|Bundler::SecurityError:.*checksum|gem may be corrupt`)}},
		{ID: "ruby-internal-error", Category: model.CategoryToolchainFailure, Provider: "Bundler", Operation: "execution", ErrorFamily: "internal-exception", Weight: 42, SignalGroup: "toolchain", Summary: "Bundler or RubyGems raised an internal deterministic exception", Recommendation: "Reproduce with the same Ruby/Bundler versions, then update or report the tool defect with the complete stack trace.", Patterns: []*regexp.Regexp{re(`Bundler::FriendlyErrors:.*(?:undefined method|NoMethodError)|bundler/.*\.rb:\d+:in .*undefined method|Gem::InternalError`)}},

		{ID: "jvm-cache-corruption", Category: model.CategoryCacheFailure, Provider: "JVM build cache", Operation: "cache-read-write", ErrorFamily: "cache-corruption", Weight: 60, SignalGroup: "cache", Summary: "The Gradle/Maven local cache or serialized resolution state is corrupt or unavailable", Recommendation: "Retry on a clean cache or fresh runner; preserve the first stack trace if the failure recurs.", Patterns: []*regexp.Regexp{re(`Problems (reading|writing) (data )?from Binary store|Corrupt serialized resolution result|Could not open cache directory|descriptor\.bin\.fslck(?s:.*?)NoSuchFileException|Problems loading the resolution results|Unknown value type read from stream`)}},
		{ID: "jvm-tls-transport", Category: model.CategoryNetworkFailure, Provider: "JVM dependency transport", Operation: "tls", ErrorFamily: "tls-handshake-failure", Weight: 58, SignalGroup: "connectivity", Summary: "A Gradle/Maven dependency transfer failed during TLS negotiation", Recommendation: "Check the remote repository, TLS policy, proxy interception, and system trust store before changing dependencies.", Patterns: []*regexp.Regexp{re(`Received fatal alert:\s*handshake_failure|SSL peer shut down incorrectly`)}},
		{ID: "jvm-version-resolution", Category: model.CategoryCodeFailure, Provider: "JVM dependency resolver", Operation: "dependency-resolution", ErrorFamily: "version-or-lock-conflict", Weight: -58, SignalGroup: "deterministic", Summary: "Gradle/Maven could not satisfy the requested dependency version or lock state", Recommendation: "Correct the requested version, lock state, repository declaration, or conflicting constraints.", Patterns: []*regexp.Regexp{re(`Cannot find a version of .* that satisfies the version constraints|not part of the dependency lock state|No cached version listing .* available for offline mode|Could not find satisfied version for SemVer|Could not find [A-Za-z0-9_.-]+:[A-Za-z0-9_.-]+:\s*(?:\.|$)|Could not find gradle:gradle:.*(?:snapshot|nightly)|Non-resolvable import POM`)}},
		{ID: "jvm-variant-resolution", Category: model.CategoryCodeFailure, Provider: "Gradle", Operation: "variant-resolution", ErrorFamily: "variant-or-project-mismatch", Weight: -56, SignalGroup: "deterministic", Summary: "Gradle could not match the requested project, configuration, or component variant", Recommendation: "Review project paths, component attributes, Java compatibility, and Gradle configuration declarations.", Patterns: []*regexp.Regexp{re(`No matching variant of .* was found|AmbiguousVariantSelectionException|More than one variant of .* matches|Project with path .* could not be found|project\s+:[A-Za-z0-9_.:-]+\s+not found|No matching configuration of project`)}},
		{ID: "jvm-plugin-resolution", Category: model.CategoryCodeFailure, Provider: "Gradle", Operation: "plugin-resolution", ErrorFamily: "plugin-not-found", Weight: -55, SignalGroup: "deterministic", Summary: "Gradle could not resolve the requested plugin", Recommendation: "Verify the plugin ID/version and pluginManagement repositories.", Patterns: []*regexp.Regexp{re(`Plugin \[id:.*\] was not found|Plugin Repositories \(could not resolve plugin artifact|plugin dependency must include a version number`)}},
		{ID: "jvm-internal-or-configuration", Category: model.CategoryCodeFailure, Provider: "JVM build tool", Operation: "build-configuration", ErrorFamily: "deterministic-tool-or-config-error", Weight: -52, SignalGroup: "deterministic", Summary: "The JVM build failed on a deterministic configuration or internal tool error", Recommendation: "Review the first IllegalState/InvalidUserData error and the build-tool version; reproduce before retrying blindly.", Patterns: []*regexp.Regexp{re(`IllegalStateException:.*(?:Duplicate key|No target component|illegal while in .* state|has no target nodes)|InvalidUserDataException:|property must be set\. Please apply|Value for metadata of project .* has not been calculated yet`)}},
		{ID: "jvm-repository-policy", Category: model.CategoryCodeFailure, Provider: "artifact repository", Operation: "repository-policy", ErrorFamily: "request-forbidden", Weight: -50, SignalGroup: "deterministic", Summary: "The artifact repository rejected the request due to permissions, method support, or policy", Recommendation: "Check repository credentials, firewall/quarantine policy, and whether the repository supports the requested HTTP method.", Patterns: []*regexp.Regexp{re(`Could not (?:GET|HEAD).*Received status code 403|Received status code 403 from server:.*(?:Forbidden|quarantined)|Requested item is quarantined`)}},
		{ID: "jvm-artifact-not-found", Category: model.CategoryCodeFailure, Provider: "JVM dependency resolver", Operation: "artifact-resolution", ErrorFamily: "artifact-not-found", Weight: -48, SignalGroup: "deterministic", Summary: "A declared JVM artifact or project dependency could not be found", Recommendation: "Verify group, artifact, version, repository declarations, and composite-build substitution.", Patterns: []*regexp.Regexp{re(`Could not find [A-Za-z0-9_.-]+:[A-Za-z0-9_.-]+:[^\s]+|was not found in https?://.* during a previous attempt|Could not resolve plugin artifact`)}},
		{ID: "toolchain-codegen", Category: model.CategoryCodeFailure, Provider: "toolchain", Operation: "code-generation", ErrorFamily: "unsupported-codegen", Weight: -42, SignalGroup: "deterministic", Summary: "The toolchain rejected or could not generate the requested code", Recommendation: "Review the target platform, compiler/toolchain version, and generated-code expectations.", Patterns: []*regexp.Regexp{re(`opcode not found|codegen.*not supported|unsupported instruction`)}},
		{ID: "toolchain-platform-unsupported", Category: model.CategoryCodeFailure, Provider: "toolchain", Operation: "process-execution", ErrorFamily: "unsupported-platform-operation", Weight: -40, SignalGroup: "deterministic", Summary: "The requested toolchain operation is unsupported on this platform", Recommendation: "Adjust the workflow for the operating system or use a supported runner/toolchain combination.", Patterns: []*regexp.Regexp{re(`exec: canceling Cmd: not supported by windows|operation not supported on (windows|linux|darwin)|unsupported platform`)}},
		{ID: "tool-internal-panic", Category: model.CategoryToolchainFailure, Provider: "build-tool", Operation: "execution", ErrorFamily: "internal-panic", Weight: 42, SignalGroup: "toolchain", Summary: "A build tool, package manager, or compiler failed internally", Recommendation: "Reproduce with the same tool version, then update or report the toolchain defect with the stack trace; do not blame the project code without further evidence.", Patterns: []*regexp.Regexp{re(`panic: Internal error|internal compiler error|fatal internal error|ERROR: Fatal Internal error|Please report as a bug`)}},
		{ID: "runtime-panic", Category: model.CategoryCodeFailure, Provider: "runtime", Operation: "execution", ErrorFamily: "runtime-panic", Weight: -36, SignalGroup: "deterministic", Summary: "The executed program crashed with a runtime panic", Recommendation: "Inspect the first application stack frame and reproduce the deterministic crash.", Patterns: []*regexp.Regexp{re(`panic: runtime error: invalid memory address or nil pointer dereference`)}},
		{ID: "compiler-go", Category: model.CategoryCodeFailure, Provider: "compiler", Operation: "compile", ErrorFamily: "go-compile-error", Weight: -45, SignalGroup: "deterministic", Summary: "Go compilation failed deterministically", Recommendation: "Fix the reported source or type error.", Patterns: []*regexp.Regexp{re(`\.go:\d+:\d+: (undefined|cannot use|syntax error|too many arguments|not enough arguments)|build failed.*go`)}, Excludes: []*regexp.Regexp{re(`proxy\.golang\.org.*(timeout|502|503|504)`)}},
		{ID: "compiler-ts", Category: model.CategoryCodeFailure, Provider: "compiler", Operation: "compile", ErrorFamily: "typescript-compile-error", Weight: -44, SignalGroup: "deterministic", Summary: "TypeScript compilation failed deterministically", Recommendation: "Fix the reported TypeScript source/type error.", Patterns: []*regexp.Regexp{re(`error TS\d{4}:|TypeScript error in`)}},
		{ID: "compiler-rust", Category: model.CategoryCodeFailure, Provider: "compiler", Operation: "compile", ErrorFamily: "rust-compile-error", Weight: -44, SignalGroup: "deterministic", Summary: "Rust compilation failed deterministically", Recommendation: "Fix the reported Rust compiler error.", Patterns: []*regexp.Regexp{re(`error\[E\d{4}\]:|could not compile .* due to`)}},
		{ID: "test-assertion", Category: model.CategoryCodeFailure, Provider: "test-runner", Operation: "test", ErrorFamily: "assertion-failure", Weight: -38, SignalGroup: "deterministic", Summary: "A deterministic test assertion failed", Recommendation: "Inspect the failing assertion and changes affecting the tested behavior.", Patterns: []*regexp.Regexp{re(`AssertionError|expected .* (to equal|but got)|Tests:.*failed`)}, Excludes: []*regexp.Regexp{re(`timeout|ECONNRESET|EAI_AGAIN|connection refused`)}},
		{ID: "test-flake-retry", Category: model.CategoryTestFlake, Provider: "test-runner", Operation: "test", ErrorFamily: "flaky-retry", Weight: 25, SignalGroup: "flake", Summary: "Test behavior indicates a possible flake", Recommendation: "Rerun the isolated test and inspect timing, ordering, network, or shared-state dependencies.", Patterns: []*regexp.Regexp{re(`flaky test|test.*is flaky|passed on retry|succeeds? on rerun|retrying failed test|test.*intermittent`)}},
	}
}
