name: Feature request
description: Suggest an improvement
title: ""
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What would you like CI Radar to do?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Anything else?
